### ISSUE TITLE
BUG: When user click outside of the popup it is not closing it

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1043]
![image](https://github.com/ever-co/ever-teams/assets/81486442/1903891c-a5ca-4879-8453-6c909bb8204b)

**Comment by evereq** [comment]
Yeah @badalkhatri0924 , I would also probably add "x" icon to close it, but I am old school :)

**Comment by badalkhatri0924** [comment]
> Yeah @badalkhatri0924 , I would also probably add "x" icon to close it (in the header of popup), but I am old school :)

So should we add "X" everywhere in popups?

**Comment by evereq** [comment]
I would prefer that, yes, at top right corner in the header of popups
