### ISSUE TITLE
[Feature] Social signups

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#1063]
We need to support the following Signup methods in addition to the basic ones we already have:

- Discord (really required as a lot of teams are using it last time)
- GitHub 💯 
- LinkedIn
- Google
- Microsoft

Of course, it's all should be done via integration with Gauzy APIs, while in Ever Teams we only maintain UI for those login / sign up flows

**Comment by GloireMutaliko21** [comment]
Resolved in https://github.com/ever-co/ever-teams/pull/2624
