### ISSUE TITLE
Task Detail page Title UI is not proper

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1085]
- Make the focus border light-colored(both LIGHT and DARK mode) (the white color border is not looking good)
- Use 100% width for the input

<img width="1437" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/99523ee3-cdb0-4e2f-bdb3-4e32be3145ae">

**Comment by evereq** [comment]
Yes same as black border on dark theme :))
