### ISSUE TITLE
Long task title is not looking good

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1107]
- Task Title can be upto **255** characters only

<img width="1439" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/8b5b437b-74d2-4f6f-8a51-bfffadc35be1">

**Comment by evereq** [comment]
Hm, I don't think so... Ideally we want to show description of task as much as possible as long as page size allows it... I.e. we should not cut description in few lines and ask user to click... When i open an issue (task) I want to be able to read full description (possible to use scrolling etc). Your screenshot above is cut so hard for me to see full picture, but again - idea is to show as much description as we have a space for it, unless some other important elements can't fit

**Comment by evereq** [comment]
@badalkhatri0924 Btw, why the description text is SO large / bold? Is it because you make it that way or it's editor default? We don't want that by default, let's use "normal" text... Like here in GitHub you can see description of issue with "normal" text :D

**Comment by badalkhatri0924** [comment]
> Hm, I don't think so... Ideally we want to show description of task as much as possible as long as page size allows it... I.e. we should not cut description in few lines and ask user to click... When i open an issue (task) I want to be able to read full description (possible to use scrolling etc). Your screenshot above is cut so hard for me to see full picture, but again - idea is to show as much description as we have a space for it, unless some other important elements can't fit

@evereq FYI: This is Task Title.

For description we are using Slate texteditor

**Comment by evereq** [comment]
oh oh oh sorry @badalkhatri0924 I thought it's description, but you mean Title :) Yes, let's make it up to for example 3 lines of text MAX.

**Comment by badalkhatri0924** [comment]
@evereq So this is how it should look if we have smaller title.

<img width="1423" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/965e25b0-9f3c-4e96-ad4e-931d6d21e492">

**Comment by badalkhatri0924** [comment]
> oh oh oh sorry @badalkhatri0924 I thought it's description, but you mean Title :) Yes, let's make it up to for example 3 lines of text MAX and use "..." so that if user click it expands fully

I think we can use tooltip?

**Comment by evereq** [comment]
@badalkhatri0924 hm, for Title, tooltip will be weird I think.....
