### ISSUE TITLE
[Fix] Border should be smooth

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1166]
### Current Implementation
<img width="120" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/d1b9bcd2-63a2-4867-a285-1cfd084aad14">

### Expected Implementation
<img width="110" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/0e40f638-4038-4005-a1af-7c7baf9a886e">

**Comment by Cedric921** [comment]
@GedeonTS  check if is full implemented, if not you can Work on
What do you think Sir @evereq / @KostyaEver

**Comment by GedeonTS** [comment]
Hi @Cedric921 , I've been searching what I can improve in the borders but I dont find anything.  I think It is allready Implemented as the pictures you provided
