### ISSUE TITLE
Bug: for tasks that are of type "Epic" we should not show selector for parent Epic

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#1234]
For the type of task "Epic" we should hide the selector of parent "Epic" in the sidebar as it does not make sense

![image](https://github.com/ever-co/ever-teams/assets/118497/13b2f6c9-47bd-4c7d-aaa8-0b89938ac8c4)

**Comment by badalkhatri0924** [comment]
https://github.com/ever-co/ever-teams/issues/1084

@evereq Duplicate issue.
