### ISSUE TITLE
Timer is running in another device but in Member Tasks page status is not showing online

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1297]
<img width="1511" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/2f07e436-17a2-47e0-ba0d-01eede541e75">
<img width="757" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/d5590e06-01a5-4a91-926e-dc1852e55906">

**Comment by evereq** [comment]
@badalkhatri0924 you probably mean "not showing online"? Because it should show member is online in all places, but from second screenshot we see it's not...

**Comment by badalkhatri0924** [comment]
> @badalkhatri0924 you probably mean "not showing online"? Because it should show member is online in all places, but from second screenshot we see it's not...

Was typo! fixed the title. Yes it should show online everywhere.
