### ISSUE TITLE
[Bug] Public Team page stop working after sometime

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1325]
If we have multiple users/tasks public page stop responding after some time.
As public page keep refreshing the data every 5 seconds but API doesn't return the responses within 5 seconds (Take ~20 seconds).
So server is getting flooded with lot of API requests and get crashed

This doesn't happed to any other authenticated pages of application and public pages of team which has less users/tasks

<img width="1036" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/8badb4db-4978-4580-a62a-8fee8f452441">

https://github.com/ever-co/ever-teams/assets/81486442/6c3cbfb7-4984-4c2c-8a9e-8ec26de08b0f

**Comment by evereq** [comment]
@badalkhatri0924 yes, because it should NOT send requests every X seconds. Instead, it should send a request and ones gets a response, wait X seconds and send the next request. We have @adkif who did that already in Desktop Apps in Gauzy :) 
Of course all that will be switched to real-time communication later, but for now let's adjust to what I just described. We can't send requests every 5 sec, it creates a "queue" of those requests and also can kill our servers very quickly :)

**Comment by badalkhatri0924** [comment]
> @badalkhatri0924 yes, because it should NOT send requests every X seconds. Instead, it should send a request and ones gets a response, wait X seconds and send the next request. We have @adkif who did that already in Desktop Apps in Gauzy :) Of course all that will be switched to real-time communication later, but for now let's adjust to what I just described. We can't send requests every 5 sec, it creates a "queue" of those requests and also can kill our servers very quickly :)

Yes @evereq I am going to fix that. Also I found another thing here, if I send all the params then only it is taking this much of time, instead I am thinking to split the param and do 2 the API requests as shown in below screenshot.

![image](https://github.com/ever-co/ever-teams/assets/81486442/a1d88f8e-d41c-48f3-a889-5f10fe878560)
![image](https://github.com/ever-co/ever-teams/assets/81486442/f6b8cad3-2eee-4912-9203-6371991901da)

**Comment by evereq** [comment]
yes, makes sense @badalkhatri0924 . I would maybe even make another request to get a list of members separated from list of tasks. I think we may run "refresh" for list of members and for statuses / priorities / sizes / labels / issuesTypes less frequently (e.g. every 30 sec) as those things rarely change, while we can refresh "tasks" more frequently and such "separation" will help with that?

**Comment by badalkhatri0924** [comment]
> yes, makes sense @badalkhatri0924 . I would maybe even make another request to get a list of members separated from list of tasks. I think we may run "refresh" for list of members and for statuses / priorities / sizes / labels / issuesTypes less frequently (e.g. every 30 sec) as those things rarely change, while we can refresh "tasks" more frequently and such "separation" will help with that?

Yes it will help.
