### ISSUE TITLE
[Enhancement] I.e. Switch between table view and card view (vertical cards)

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1426]
Make a different view of the page. User cards will be like cubes or similar - so that we can see more users on one screen.
I.e. we can have a switch between table view (now) and card view (vertical cards)

**Comment by maceteligolden** [comment]
@badalkhatri0924 is there a design for this. i would like to implement it

**Comment by badalkhatri0924** [comment]
> @badalkhatri0924 is there a design for this. i would like to implement it

https://github.com/ever-co/ever-teams/issues/1619
https://github.com/ever-co/ever-teams/issues/1620

@maceteligolden , @YehualashetGit is already working on this thing.
