### ISSUE TITLE
[Feature] 'All Teams' management

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#1433]
As a Manager, I should be able to see employees in All Teams I manage them on the same screen view.
If I am owner of organization, I will be manager of all Teams too and so I will see all stats for all teams, but if someone manage only 2 teams, she will see info for 2 teams

Once in team Selector, the manager selects 'All Teams', and the manager can see teammates split per team.

The main input and the time tracker are hidden

<img width="479" alt="Screenshot at Sep 25 11-02-54" src="https://github.com/ever-co/ever-teams/assets/107203576/dc0c8a98-5369-4835-8204-5395f9ee96ab">

**Improvement**: Would be nice to have a mini filter, where the manager can click 'Now' (The manager can see only unique employee records where s/he is working now, in case employee works on more than one project/team) 
the filter should search by 'All' / 'Now' / 'Paused' / 'Off' / 'Invited' (multi-select dropdown)

For UI we have 2 options for cards:
a) "combine" information around one member into one card as I described above
OR
b) display one team below another, e.g. Team A and members of it, below Team B and members of it (and that way same member can be displayed few times but for different teams / tasks).
We can also add switch that will allow to switch quickly between a) and b) views

**Comment by KostyaEver** [comment]
For 'Combine' option probably need a way how to display the 'current project' @evereq

**Comment by KostyaEver** [comment]
it should also be available for people who are "Managers" of few teams! E.g. if I am manager in Team A and Team B, when I select "All Teams" I should see cards for both Team A and Team B "distinct" so same person did not show up few times, but instead one card for person show tasks from few teams and show clearly which one person is working on now
 
 needs to  be discussed later

**Comment by evereq** [comment]
@KostyaEver please talk with @JoeMakuta to create any designs in Figma for this if needed.
