### ISSUE TITLE
[Bug] Settings UI

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#1435]
1. The action ( ... ) menu should be aligned with each user record

Note: Seems like only the first record aligned with the action menu. Make sure the list of Invited and Members has an aligned menu

2. If the user clicks 'edit', it extends 'Name' column, Should not extend the size of the column

<img width="1225" alt="Screenshot at Sep 25 14-32-11" src="https://github.com/ever-co/ever-teams/assets/107203576/c8c9066e-f6a9-476a-b81c-4c0ca9fbce70">

**Comment by badalkhatri0924** [comment]
@KostyaEver If possible can you attach video too?

**Comment by KostyaEver** [comment]
Sure @badalkhatri0924 https://www.loom.com/share/4ca1fe26ddde4cd29fd94a8c5c8d1a1b?sid=9f58296a-9e8f-4bea-aa59-1874f09c2a8d

**Comment by badalkhatri0924** [comment]
@KostyaEver I've fixed this issue. Please check this later today, once new build is released.
