### ISSUE TITLE
[Enhancement] Tasks View/Create Logic

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1547]
**`Task Creation - Project/Team Mapping`**

- When user create task, always associate it with BOTH project and Team(If Applicable)
- IF (projectId == currentProjectId and organizationTeamId == null) OR (projectId == currentProjectID && organizationTeamId = currentTeamId) THEN show task (In Ever Teams)

**Comment by evereq** [comment]
@paradoxe35 can you check if it's fully done / implemented please? If yes, close ticket.

**Comment by paradoxe35** [comment]
@evereq 
We can close this ticket.
Implemented
