### ISSUE TITLE
[Bug] Invalid "Worked On Task"/"Total Worked Task"

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1592]
<img width="1501" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/6a31464e-d333-42f6-8783-72d21d9a3bd3">

**Comment by evereq** [comment]
@GloireMutaliko21 can you check if it's still wrong values or not? If not, let's close this ticket.

**Comment by GloireMutaliko21** [comment]
Closed in #2683
