### ISSUE TITLE
[Feature] Table view for Issues

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1619]
According to Figma.

Let's not do for now that "Filters" block (with tons of comboboxes), we need our designer to still work on it to improve it (such view available in another Figma slide) (edited) 

I think what we should do is:
Figure out what table component we should use, e.g.
https://ui.shadcn.com/docs/components/table looks too simple to me, we may want to search for MIT / Apache 2.0 licensed popular table component for React / NextJs, maybe?

2. On our Home page add switch between "Card" view (current one) and "Table" view (new one)

E.g. add in that place I highlighted 2 icons - for Cards and Table
![image](https://github.com/ever-co/ever-teams/assets/81486442/f7d4376e-051a-4d7d-b75a-7c5e4ed2ded5)

(default should be current view)

3. Of course in the table view the "task input / timer" should also stay on the page, it's only CARDS below should change to TABLE view

4. Designer forgot to add "Labels" below tasks, we need to have that similar to cards view

5. We need to somehow also add there "Estimate" data, same as we have it in the Cards view

6. We also need to add timing information from "Worked on Task" column

(no need to add Total worked Today because that view is more focused on issues than people)

7. Of course to improve table view with more such as assignee email etc

8. "..." menu for each table item should work same way as for another view

9. Note that while each issue can have more than 1 assignee, in that specific view we always show a person who working on issue NOW / worked on it last time, same as we do it on existed view page. I.e. even so that view called "Issues" and it shows ISSUES that people working on, in reality for each Team member we show one ROW in the table with issue information on which s/he worked on. We should NOT display there issues that nobody worked on, we will have another page for that called "All Issues". Same we do NOT display here issues that not assigned to anyone in the team. However (important!) we should display rows with empty "issue" field for team members who don't have issues assigned yet and allow to quickly assign issues from that table view to such people (e.g. click inside that empty space and assign issue to that person, essentially displaying Popup where it's possible to select issue from the list)

**Comment by Cedric921** [comment]
Completed by #1426
