### ISSUE TITLE
[DevOps] Deploy to Render

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#1621]
See same in https://github.com/ever-co/ever-gauzy/issues/4055

We can use GitHub action https://github.com/marketplace/actions/render-deploy-action

**Comment by maceteligolden** [comment]
@evereq for this are we trying to only deploy web or everything?

**Comment by evereq** [comment]
@maceteligolden only Web frontend for this project. Backend deployed as part of Gauzy for which we have that separate issue (link was added by me in the issue description)

**Comment by maceteligolden** [comment]
https://github.com/ever-co/ever-teams/pull/1671

**Comment by maceteligolden** [comment]
@evereq i think we can make use of render's deploy hooks. this doc says it works with github actions https://render.com/docs/deploy-hooks

**Comment by evereq** [comment]
@paradoxe35 we actually did that already, see https://github.com/ever-co/ever-teams/blob/develop/render.yaml and even added button to README. So it's more like to review it all and see if we can (need) to improve anything etc.

**Comment by evereq** [comment]
I also see https://github.com/ever-co/ever-teams/compare/feat/render-deployment-action?expand=1, but I don't like much that, i.e. not sure what it provides etc. Ideally of course we would like to have some sort of such GitHub action that deploy everything to render so we can see status of deployment directly in Actions etc. But I don't think that's right approach in that specific code, maybe we need to use https://github.com/marketplace/actions/render-deploy-action instead?
