### ISSUE TITLE
[Bug] Infinite network requests occurring after login

### ISSUE THREAD

**Issue by NdekoCode** [ever-co/ever-teams#1635]
I have noticed a network error in the application where there are infinite requests occurring once a user is logged in. This can be observed in the browser's network tab. I suspect that there might be a `useEffect` hook without any dependencies, causing it to run constantly. It's worth mentioning that this network error is not present on the authentication pages.

Steps to reproduce:
1. Log into the application.
2. Open the browser's network tab.
3. Observe the continuous stream of network requests being made.

Expected behavior:
The application should not make infinite network requests after logging in. Actual behavior:
The application makes continuous network requests, leading to performance problems and slowdowns.

Please let me know if there is any additional information needed to investigate and resolve this issue.

**Comment by badalkhatri0924** [comment]
@NdekoCode I checked out develop & improve/internationalization branches, it is working fine for me.

Can you try again? Any specific trigger point which causes the issues?

**Comment by NdekoCode** [comment]
Yes sir @badalkhatri0924 , once you're connected and the application is up and running, you can go to the network tab, then just check the filter by "XHR" and wait, you'll see the requests start without stopping.
I noticed it when I was trying to detect the loaded translation file.
At first, I thought it was because I was local, but this problem is also present in production on the online application `https://app.ever.team/`, and that's when you're connected too.

**Comment by badalkhatri0924** [comment]
@NdekoCode not sure why, but it works fine for me.
