### ISSUE TITLE
[Enhancement] Enable/Disable ReCaptcha based on ENV Variable

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1637]
we have to make sure ReCaptcha IS disabled, unless corresponding env var set.

If env vars are NOT set, we should DISABLE reCaptcha and allow anyone to use Ever Teams without ReCaptha checks etc. If env vars ARE set, it should enable ReCaptcha and use it

**Comment by maceteligolden** [comment]
@badalkhatri0924  can i close this issue?

**Comment by badalkhatri0924** [comment]
> @badalkhatri0924 can i close this issue?

yes
