### ISSUE TITLE
[Enhancement] Update NextJs to latest

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#1641]
I think it's time to update the NextJs version to the latest, please see PR https://github.com/ever-co/ever-teams/pull/1638 for example. Let's try to update the package / other depts and see what code changes are required to make it all work well. Please do update only in /web folder (because we are moving website to separate repo)

**Comment by maceteligolden** [comment]
@evereq alright

**Comment by maceteligolden** [comment]
@evereq  can i close this issue?
