### ISSUE TITLE
Feature: integrate Auth library for support of social logins and more

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#187]
So we are using currently Auth on top of Gauzy API. 

I wonder if we can at some point use https://github.com/nextauthjs/next-auth TOGETHER with Gauzy API. I.e. so that we use the power of that Next Auth package (especially for social logins with FB, Google, Github, etc), but still make sure tokens we get come from Gauzy API too so that they can be used to access later Gauzy APIs. 

They have also a NextJs sample project https://github.com/nextauthjs/next-auth-example (sharing here with @channel in case if someone has had similar experiences in the past). I think we might need to create our own "adaptor" for Gauzy API, similar to how they have many adaptors already built (see https://github.com/nextauthjs/next-auth/tree/main/packages for packages start with adapter- name). Alternative to Next Auth could be Passport lib https://github.com/jaredhanson/passport with React Oauth2 https://github.com/jaredhanson/passport-oauth2 and some others, but I think it's an "older" route.

So how I see it might work:
1. Next Auth client side inside Ever Teams frontend (with multiple ways to login, including email+password, Google, FB, Github, etc) -> Next Auth inside Ever Teams backend (NextJs) -> Adaptor for Gauzy API (custom build adapter)-> Gauzy APIs
**OR**
2. Next Auth client side inside Ever Teams frontend (with multiple ways to login, including email+password, Google, FB, Github, etc) -> Gauzy APIs

**Comment by evereq** [comment]
This ticket is implementation for https://github.com/ever-co/ever-teams/issues/1063

**Comment by evereq** [comment]
@GloireMutaliko21 I did not checked your PR yet (as it's Draft), but I think we may need to implement Adaptor https://next-auth.js.org/tutorials/creating-a-database-adapter / https://authjs.dev/guides/creating-a-database-adapter which instead of talking to some DB will talk to Gauzy APIs? Basically if we implement such an adaptor for AuthJs, anyone will be able to use it for any products that require Auth with Gauzy APIs in my understanding, so maybe later on we can publish it as a separate package. 

CC: @rahul-rocket

**Comment by GloireMutaliko21** [comment]
> @GloireMutaliko21 I did not checked your PR yet (as it's Draft), but I think we may need to implement Adaptor https://next-auth.js.org/tutorials/creating-a-database-adapter / https://authjs.dev/guides/creating-a-database-adapter which instead of talking to some DB will talk to Gauzy APIs? Basically if we implement such an adaptor for AuthJs, anyone will be able to use it for any products that require Auth with Gauzy APIs in my understanding, so maybe later on we can publish it as a separate package `@gauzy/auth-adapter` and use it in the Ever Teams, etc. (it's next step, not right now!). See code for existed AuthJs adapters at https://github.com/nextauthjs/next-auth/tree/main/packages (`adapter-*`)
> 
> CC: @rahul-rocket

Got it sir @evereq ! For this feature, we'll need to add other tables on the Gauzy database and create more APIs. Would you like me to start working on it right away?

**Comment by GloireMutaliko21** [comment]
Btw, the PR is still Draft ...

**Comment by evereq** [comment]
Hm, I don't think we need to do any changes in Gauzy DB and I think you misunderstand how adapter will work - it will not connect to DB, but to Gauzy API !! @GloireMutaliko21 lets discuss in Slack
