### ISSUE TITLE
[Bug] Bottom Navigation "Tasks" 

### ISSUE THREAD

**Issue by desperado1802** [ever-co/ever-teams#1892]
When "Tasks" icon is pressed at all times we should navigate to currently logged in user's tasks, instead to the last user tasks we viewed

Also we should re-arrange the order of icons:

1. My Work
2. Teams
3. Tasks

**Comment by evereq** [comment]
And also rename "My Work" to just "Work"

**Comment by evereq** [comment]
@desperado1802 we discussed order in Slack to be :
- Work
- Tasks
- Teams 

:)))
