### ISSUE TITLE
[Improvement] Team Danger Zone disabled in some conditions

### ISSUE THREAD

**Issue by desperado1802** [ever-co/ever-teams#1917]
- Transfer Ownership: Disabled if there are NOT more than 1 manager in the team and current user is manager
- Remove Team: Active only if the count of managers is 1 and current user is manager 
- Quit Team: Current User is manager and length of managers is more than 1 OR is not manager 

![File](https://github.com/ever-co/ever-teams/assets/124465103/ff20dd49-1fda-4027-b49a-1259f1f0c7a3)

**Comment by rahul-rocket** [comment]
@desperado1802 Can you please create task in API side too? Of course, we have to do it on API side too.
