### ISSUE TITLE
[Feature] View Mode icons improvements

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#1991]
See screenshot:
![image](https://github.com/ever-co/ever-teams/assets/118497/91b38d8e-0a46-4dc1-afad-82ef67d50239)

1. Try to add text near each icon to explain view type: 
- Cards
- Table
- Blocks
- Kanban

Note: if does not look well, please just use tooltips!

2. Add "Kanban" icon (with text "Kanban", already described above) and make sure it route to https://app.ever.team/kanban

**Comment by maceteligolden** [comment]
https://github.com/ever-co/ever-teams/pull/1992
