### ISSUE TITLE
[Feature] Public Member Profile page improvements

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#2103]
- show various stats
- I would like to add "Activity" using some library (see comments below)

See below an example from our Figma (note: exact look will be defined by library you use, do NOT spend time to make it exactly like in Figma please in terms of functionality!)

![image](https://github.com/user-attachments/assets/f614a896-9c01-4bb9-8750-ccaef2472f8f)

**Comment by evereq** [comment]
Check that package above and think how we can use on Activity (which displays work time / screenshots etc). Design in Figma and show for review.

**Comment by JoeMakuta** [comment]
Hello @evereq 

The package https://github.com/williamtroup/Heat.js does not have typescript and its npm package is not well documented to be used in nextjs.
I'm looking for some alternatives.

**Comment by Cedric921** [comment]
- https://echarts.apache.org/examples/en/editor.html?c=calendar-heatmap&lang=ts
- https://cal-heatmap.com/

**Comment by evereq** [comment]
OK, so we have now a list with those:
- https://nivo.rocks/calendar (just found it and looks cool, plus they have tons of useful components under https://nivo.rocks)
- Recharts based https://ui.shadcn.com/charts - however I can't yet find this type of chart there, maybe it will be one day
- https://echarts.apache.org/examples/en/editor.html?c=calendar-heatmap&lang=ts
- https://cal-heatmap.com
- https://github.com/williamtroup/Heat.js - not sure why @JoeMakuta had issues to integrate this one, seems to be written in TS, so not sure...

**Comment by CREDO23** [comment]
@evereq, which data should be taken in account for the chart ?

**Comment by evereq** [comment]
@CREDO23 similar to GitHub :), but in terms of worked hours daily. More worked hours, more "blue" rectangle, less work hours, less "blue" rectangle, did not work at all - while. Same, we can also put there another metric of "closed" tasks qty or some others, we will define a list. But I think for start we can just use time tracking data per day for given member.

**Comment by CREDO23** [comment]
@rahul-rocket, I need an API for this task !
