### ISSUE TITLE
[Feature]: Navigation header in kanban screen

### ISSUE THREAD

**Issue by Anishali2** [ever-co/ever-teams#2193]
Add the header navigation tabs into kanban screen

**Comment by tusharwebd** [comment]
Hi @Anishali2! I am a new contributor here and would be interested to work on this. If possible, can you add some screenshots of the screenview where we need to add navigation tab? Any code references of the header tab and kanban page would also help. Thanks!

**Comment by evereq** [comment]
Hello @tusharwebd , this project is "Open" code, but not an open-source license, so we can't accept such contributions at the moment, unless you join our team full-time ;)
