### ISSUE TITLE
[Enhancement]: modify linting.

### ISSUE THREAD

**Issue by Anishali2** [ever-co/ever-teams#2195]
Modify the linting process and add the process into commit so every time you should have to fix errors before publishing

**Comment by evereq** [comment]
@Anishali2 we suppose to have already `husky` package for that, no? https://github.com/ever-co/ever-teams/blob/develop/package.json#L20

**Comment by Anishali2** [comment]
Yes we have but I have to add type script check (tsc) and eslint before commit 
It waste a lot of time when we push and after pull request it shows you have eslint errors
