### ISSUE TITLE
[Improvement]: Translation on ShotCut Modal

### ISSUE THREAD

**Issue by Cedric921** [ever-co/ever-teams#2270]

**Comment by evereq** [comment]
@GedeonTS can you check whole app and see if we "hardcoded" text anywhere and use translations? Starting from this "Modal" (@Cedric921 probably can share) but going over all files in the project (web app) and see if we missed translations and fix that? Please do it step by step, i.e. with small DAILY PRs that fix more and more.

**Comment by Cedric921** [comment]
https://github.com/ever-co/ever-teams/assets/83704005/390c751b-a3db-4cc1-9689-79626ee18d4f

**Comment by GedeonTS** [comment]
Thanks for the clarification @Cedric921

**Comment by Cedric921** [comment]
Fixed  #2487
