### ISSUE TITLE
[Feature]: modifications in kanban 2

### ISSUE THREAD

**Issue by Anishali2** [ever-co/ever-teams#2277]

**Comment by Cedric921** [comment]
Fix also this error related to Props `data-isDragging` for Draggable and Droppable Props (in camel Case) in `apps/web/lib/components/Kanban.tsx` lines : 138, 140, 207 ...

> Warning: React does not recognize the `data-isDragging` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-isdragging` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by Anishali2** [comment]
Sure I can remove that basically I don't added this thing but I can remove that
