### ISSUE TITLE
[Question] Should we remove unused shadcn components?

### ISSUE THREAD

**Issue by Anishali2** [ever-co/ever-teams#2300]
There are only 10-15 files where shadcn is used and a lot of components are just using space in the project...

**Comment by evereq** [comment]
Hm, and what we should use instead? I thought to actually use it more and more instead of removing it.... @Anishali2

**Comment by Anishali2** [comment]
Sir shad cn require additional configuration for every project I'm studying the project theme design and make components accordingly from chadcn

**Comment by Anishali2** [comment]
there are more then 10 shadcn components and libraries that are installed but not used

**Comment by evereq** [comment]
@Anishali2 please add here the path for those components, i.e. which folder they are located etc.
Still, what I think that we probably very soon will end up with usage of all of them in the project anyway.
Of course we can remove them and add again when needed too, but that way devs may forget to even check them when needed...
I would prefer to just let all devs to know that if they need components, take a look into folder A and build your components on top of shadcn (or others that we may have already added too, like headless UI, etc

**Comment by Anishali2** [comment]
Ok Sir I'm not changing any thing but if you agree let me just remove some of these 

 '@radix-ui/react-hover-card';  this lib is used in `components/ui/hover-card.tsx` and hover-card component is not used 
 
 '@radix-ui/react-dialog' this lib is used in `components/ui/command.tsx` and command component is not used 
 
 'react-day-picker' this lib is used in `components/ui/calendar.tsx` and calendar component is not used  
 
 '@radix-ui/react-avatar' this lib is used in `components/ui/avatar.tsx` and avatar component is not used.

**Comment by evereq** [comment]
@Anishali2 let's keep for now all components in the `components/ui` folder, even those that are not used yet. We will probably move it later into some separate package to be reused across projects etc. I am closing this ticket for now. Thank you!
