### ISSUE TITLE
[UI]: Add styled scrollbar across multi-scroll pages.

### ISSUE THREAD

**Issue by Anishali2** [ever-co/ever-teams#2355]
![image](https://github.com/ever-co/ever-teams/assets/105014311/5a70a53b-b04c-44c6-9253-1216b86b0a0b)

**Comment by evereq** [comment]
@Anishali2 actually I said before in Slack that we may NOT want to change those 2 "main" scrollbars and only want first to change scrollbars that are "secondary", i.e. not main! E.g. on Settings, where you have one scrollbar at left sidebar that can be thin and main scrollbar at right side that we can keep standard for now... etc

**Comment by Anishali2** [comment]
Ok Sir Now I got it

**Comment by Anishali2** [comment]
This Issue is fixed https://github.com/ever-co/ever-teams/pull/2362
