### ISSUE TITLE
[Feature] Ability to add tasks to 'Daily Plan's

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2393]
each task has an Action ( ... ) menu on pages:
- User Profile (tabs Worked, Assigned, Unassigned)
- Kanban

should add a divider with the other action options

**Important**: Properties (Plan Today/Tomorrow/Saomeday) should be visible only for tasks with assignees. if task already planned should see only 'Unplan' property

Options:
- Plan For Today
- Plan For Tomorrow
- Plan For Someday

Plan For Today
- Should simply add a task to the today plan (and so that task will be shown in the user tab 'Daily Plan'). If plan not exists yet for today, create it.

Plan For Tomorrow
- Should simply add a task to the tomorrow plan (and so that task will be shown in the user tab 'Daily Plan').  If plan not exists yet for tomorrow, create it.

Plan For Someday
- Should simply make a record for that task when it is planned for some future date (ask the date!)  and such task will be displayed in Daily Plan for that date. So when user click this option should see calendar with dates/months and be able to select the date

**How user can 'Unplan' task**
if the Task is already planned for the user, should see only the option 'Remove from XXX Plan' for this task (where XXX is "Today" or "Tomorrow" or some specific Date when task was planned"

The action should be available on page User Profile and Kanban board
 
<img width="672" alt="Screenshot at Apr 30 15-33-54" src="https://github.com/ever-co/ever-teams/assets/107203576/1774c573-070f-467c-81f1-92d8b8ed1658">

<img width="695" alt="Screenshot at Apr 23 17-44-54" src="https://github.com/ever-co/ever-teams/assets/107203576/91f183cb-4c65-4c4e-862d-4843c21a4049">

**Who can plan tasks**

Plan task can ONLY assigned task

**Can be regulated by Role**

- 'Employees' can see in Action (Plan Today/Tomorrow/Someday) and create only OWN plan
- 'Manager' can see in Action (Plan Today/Tomorrow/Someday) and create only OWN plan as well as team members'

Here's where (pages) tasks can be planned https://github.com/ever-co/ever-teams/issues/2444

**Comment by GloireMutaliko21** [comment]
Hello sir @evereq, Hello sir @KostyaEver 
According to the issue https://github.com/ever-co/ever-teams/issues/2391, It seems that a plan can be only created for employees. I implemented the APIs in that way. So from API side, managers don't have the "employeeId", they are not employees. Are there some refacts we want to integrate on global design of the Daily Plan feature ?

**Comment by evereq** [comment]
@GloireMutaliko21 from what I recall, in Ever Teams Managers also have employeeId, i.e. they are Employees with Role "Manager". When a new user register in Ever Teams I think we make that user an admin in new tenant, but we also create employee record for such user so she/he can track time and be a manager etc.  @rahul-rocket probably can check more on Gauzy API side...

**Comment by GloireMutaliko21** [comment]
All right sir @evereq ! Let me check all of this, Thanks
