### ISSUE TITLE
[Feature] Task details - Add 'Planned' block

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2394]
Add a new block "Planned" with the following information (below block of "Assignees" / Start Date / Due Date please!)

- Date 
- Who will work on this task (i.e. for whom it's planned)

<img width="1078" alt="Screenshot at Apr 30 15-36-51" src="https://github.com/ever-co/ever-teams/assets/107203576/3945228a-d6f2-41fe-b1f6-1f8e6bf4e27e">

**Comment by KostyaEver** [comment]
I am looking at the task and I see that 'Start date' is the same as 'Planned' so the only difference is if we have multiple Assignees we need few 'Start dates' etc anyway the same idea as 'Planned'.

So what I think when the user clicks 'Plan for Today' or 'Plan for Tomorrow' or 'Plan for Custom' the system sets the appropriate 'Start date' and if it has estimation, 'Due date' can be calculated/suggested automatically

@evereq

**Comment by evereq** [comment]
@KostyaEver yes correct and just a note that "Start Date" is not same as "Planned Date" right? I.e. Start Date is when person STARTED work on this task, but Planned Date is just a date when s/he MAY start work on the task. So those are 2 separate things and we should keep them separate. Also, I like idea that same ticket can have few planned dates! E.g. if employee E1 planned it for Date D1, and employee E2 planned it for Date D2, it's actually will be displayed as 2 rows.
