### ISSUE TITLE
[Bug] Does NOT work member Status indicator

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2406]
User who are actively tracking time should have 'Green play' icon on Avatar

'Red' should be for whose who are not active at all current day (not tracked time)

<img width="1666" alt="Screenshot at Apr 24 12-54-00" src="https://github.com/ever-co/ever-teams/assets/107203576/32e17c2e-bfea-4576-9fb3-f0056db5740f">

Expect:
User who are online                                          - should have 'Green' + 'stop' indicator
User who are online and tracking time           - should have 'Green' + 'play' indicator
User who are offline, not worked ye Today    - should have 'Red' stop indicator
User who are offline and tracked time today - should have 'Orange' pause indicator
User who are suspended by manager            - should have 'Grey' stop indicator

Note: related task with Statuses definition https://github.com/ever-co/ever-teams/issues/756

**Comment by paradoxe35** [comment]
@KostyaEver 
Could please again on your side, because it worked on my side side

https://www.loom.com/share/58f62ac98d694be8aaf7b39d8038d1bf
