### ISSUE TITLE
[Bug] Kanban | Task worked Time issue

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2411]
'Live' time - should show only when someone tracking time on the task right now.

Note: the main purpose of that 'Live' time to display in real-time working progress on the task (such column is defined in Settings)

If user did not track time on task now, it should be displayed as 'Worked' time (i.e  that mean that Nobody is tracking time at the moment towards such task). 

So, usually, the tasks on Dashboard where members are tracking time should be with the same status 'In progress', but it is possible that such tasks can be in other columns too, see comments below!

It should display Hours / Minutes / Seconsd ONLY for cards with LIVE, but for "Worked" is ok to display ONLY hours and minutes. NO need 'seconds' for 'Worked'! That's because for LIVE we want to show it in real-time as it changes and seconds are useful for that. 

<img width="769" alt="Screenshot at Apr 24 16-13-00" src="https://github.com/ever-co/ever-teams/assets/107203576/1b93f666-3c4d-4536-9314-4f5f1fb8534d">

**Comment by evereq** [comment]
I don't agree with that approach @KostyaEver , it makes unnecessary restrictions. 
For example, we may have tasks with the status "IN REVIEW" or status "TESTING NOW" and we do want someone to track time on such tasks and we should see indication of how much time tracking in real-time on such tasks etc! 
So essentially "Live" can be displayed on ANY status WHEN someone tracking time towards that task! 
And "Worked" should be displayed for tasks on which nobody working now.
Please correct the ticket description accordingly.

**Comment by KostyaEver** [comment]
if you remember we approved approach that when user start tracking time it changes status to 'in progress' for any task.

For QA we can add the same logic for column/status 'Review' but it does not make sense for status/column 'Open'/'TODO' OR 'Done' to have such 'Live' time

@evereq

**Comment by evereq** [comment]
Again, change of "Status" inside Ever Teams when user start tracking does not mean that tasks can't be in other columns and be live! E.g. it is possible someone tracking those tasks in Desktop App and the status is "IN REVIEW" for example. Or another example, in the Settings someone DISABLE that feature to automatically switch task to IN PROGRESS" when timer start!

**Comment by evereq** [comment]
@KostyaEver I updated task description according to my comments above
