### ISSUE TITLE
[Bug] Kanban | task Action menu

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2413]
Now when the user click Action ( ... ) menu on task card, the system opens popup 'Assign task' (does not make any sense)

Should be next

- Edit (as it is NOW)
- Copy Issue link (copy link to clipboard)
- Make a Copy (should create the copy of task just different 'Number' and add word [copy] to the beginning of a title)
- Assignee (open small multi-select dropdown with all team members)
- Change Parent (change current Epic or parent issue
- Change Relations
- Set as Next (should set as next task in order to work on)
- Move to (change more globally location of the task with in project - will be described later)
____________
- Plan for Today
- Plan for Tomorrow
- Plan for Someday

<img width="591" alt="Screenshot at Apr 24 16-35-00" src="https://github.com/ever-co/ever-teams/assets/107203576/412bf05b-76ba-4bdf-870e-b1e490e20c0f">

**Comment by evereq** [comment]
@KostyaEver please create separate task for those that related to the Daily Plan and remove from here. I know you tried to keep it in one place, but I would prefer someone to handle the whole "Daily Plan" functionally separately

**Comment by KostyaEver** [comment]
@evereq task already created - here is more like to  add more options to in the UI as placeholedr. since it is the same Action ( ... ) menu.

**Comment by KostyaEver** [comment]
Let's simply keep as main functionality all related to 'Daily Plan' the rest let it be as placeholders.

What do you think @evereq ?

**Comment by evereq** [comment]
Maybe API is not deployed yet to production @Anishali2 , we have to wait till we can deploy Gauzy latest version :) 
Meanwhile if you run it locally, you can connect to https://apidemo.gauzy.co/api/health and check it or run Gauzy API locally :)
