### ISSUE TITLE
[Improve] The user is able to resend the confirmation code indefinitely

### ISSUE THREAD

**Issue by GedeonTS** [ever-co/ever-teams#2431]
![Screenshot from 2024-04-25 15-05-14](https://github.com/ever-co/ever-teams/assets/97834160/5c779c6f-c0c9-4789-abcd-4fd4a9f4578e)

**Description**:The user is able to resend the confirmation code indefinitely without having any changes or animations in the UI.

**Steps to Reproduce**:
Create a new account or just login with an existing one but when don't type the confirmation code yet, instead, try clicking several times on the "resend code" button and check your emails.

**Current Behaviour:**
The user receive several confirmation codes after clicking several times on the "resend code" button.

**Expected Behaviour**:
The "resend code" button should either be deactivated or replaced by a short timer to prevent this situation.

**Comment by evereq** [comment]
Yes, we should deactivate resend button for say 1 min and add counter that decrease so user can see when s/he can click resend next time @GedeonTS  (i.e. counter will show 00:59, 00:58, and so on till resend link become activate again)
