### ISSUE TITLE
[Feature] Tab 'Outstanding' on Daily Plan

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2445]
The main aim of the feature is to help managers to manage tasks that were not started and not completed, but were planned.

Users can see the 'Outstanding' section in v.1 on page User Profile, tab 'Daily Plan'

For V.1

So if a plan contains tasks with "Uncompleted" (i.e. tasks are uncompleted) and "Not started", then it should appear in the 'Outstanding' section (from which the user will be able to add tasks to the new planned day!).
So idea is that the project should try NOT to have uncompleted tasks, but if they exist, it should be easy to move them to the next day to work on them.

So when a planned date passed. All tasks with statuses (TODO, In progress, Paused, Blocked etc) should be displayed in the 'Outstanding' section.

**Note**: the system should NOT move a task to Outstanding and remove it from that plan, NO. 
"Outstanding" just serves as a list (reference) of uncompleted tasks to be able to replan for another day!!

**Important**: How tasks get to tab 'Outstanding', All tasks that have status (TODO, In progress, Paused, Blocked - specific statuses - should be defined in Settings) on the next day when time crossed 0:00 AM should appear in 'Outstanding' tab

<img width="892" alt="Screenshot at Apr 30 17-22-55" src="https://github.com/ever-co/ever-teams/assets/107203576/d83699ef-42e3-45d0-b60f-da3ecfa440cc">

**Comment by evereq** [comment]
@KostyaEver I updated description a bit to make it more readable.
