### ISSUE TITLE
[Bug] Estimate | UI inputs fix

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2447]
The issue is that UI is inconsistent now

<img width="1541" alt="Screenshot at Apr 29 12-30-45" src="https://github.com/ever-co/ever-teams/assets/107203576/c4a796e7-9297-4a1b-8bd9-87e15700e36d">

How it should be

Users can see 'Estimate' section in two conditions

1. View

2. Edit

- By default task estimate inputs are empty and show __ h __ m. (do not show `0 h 0 m` by default!)

- in Edit mode if value not entered yet should have: __ h __ m (so that the user knows where to add values)

- where there is an estimate it should have: 1 h 10 m (digits are examples)

- it's OK if user only enter hours and did not enter minutes value and "save" it. In this case, we should automatically set minutes to 0. For example input was empty and I entered 5 h and not entered anything in minutes and saved. After that it should show 5 h 0 m

- similar to above, but for case when user enters only minutes and did not enter hour value! In such case, it should set hour to 0 automatically.

**Comment by evereq** [comment]
@Anishali2 / @KostyaEver I updated ticket description to add a bit more info. Basically, I am NOT sure why this cause so much confusion. User should be able to enter one of values (hour or minute) OR both values (i.e. both hour and minute value) and it should save. By default it should just show empty so user understand that s/he can enter estimate if needed. etc. All very much logical and easy UX / UI (and as usual code with a lot of logic and bugs for such simple thing, haha)

**Comment by KostyaEver** [comment]
now it works as expected from the task
