### ISSUE TITLE
[Bug] Settings | UI, user can scroll out of page

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2452]
The issue is that the user can scroll pages out of defined layouts of the Settings page..

Steps to reproduce
1. Open Settings
2. Find 'Members & Roles' block
3. Click on 'Action ( ... ) menu' area (in RED) It opens action in the very bottom of the page
4. Hover the area below the page ('Footer' like)
5. Scroll down/up

**Expect**: 'Action ( ... ) menu' should open the next to the record and ' ... '

<img width="1650" alt="Screenshot at Apr 29 15-49-04" src="https://github.com/ever-co/ever-teams/assets/107203576/9cf6afcc-e3fc-4558-a0cd-a4d6064b7ace">

<img width="1652" alt="Screenshot at Apr 29 15-52-20" src="https://github.com/ever-co/ever-teams/assets/107203576/0783b9d5-a5f3-4967-bb32-94004af35a60">

<img width="1653" alt="Screenshot at Apr 29 15-43-39" src="https://github.com/ever-co/ever-teams/assets/107203576/f8eb0c47-5c78-4fe3-ab7f-9b9f8d053ed3">

**Comment by evereq** [comment]
@Anishali2 I remember you tried to fix it many times and always something new .... Can you fix it one time for all cases? And also without any large changes if possible? I.e. just really fix and test it very well?

**Comment by Anishali2** [comment]
Sir, I checked every dropdown on this page in the previous PR I also don't know why this is happening again and again.
Let me fix this again
