### ISSUE TITLE
[Bug] Settings | Can't create New Status

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2453]
The issue is when the user has already given a Name + color + icon for a Status, by clicking 'Create' nothing happens.

Expect: user should be able to create New Status if needed.

**Important**: The number of columns on the Kanban board should be the same as Statuses

<img width="1592" alt="Screenshot at Apr 29 15-58-30" src="https://github.com/ever-co/ever-teams/assets/107203576/bb6224e5-f353-4759-a1a1-3a30a3fafb36">

**Comment by rahul-rocket** [comment]
@Anishali2 I have checked, so you have missed an parameter `value` in request payload. So request parameter should be like below.

Endpoint: `{{url}}/api/task-statuses`
Method: POST

```
{
    "name": "READY",
    "value": "ready",
    "organizationId": "{{UUID}}",
    "tenantId": "{{UUID}}"
}
```
