### ISSUE TITLE
[Bug] Dashboard | Create New task issue

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2455]
The issue is that user can't create a new task in the main input.

When a user tries to create, the system just overrides the selected by-user task

TES-13 task 24 (current)

<img width="1636" alt="Screenshot at Apr 29 16-44-24" src="https://github.com/ever-co/ever-teams/assets/107203576/66f8d951-c978-478b-8b8a-076af28af8af">

task 25 (New, does NOT exist) should TES-'NEW' task 25

<img width="1628" alt="Screenshot at Apr 29 16-44-59" src="https://github.com/ever-co/ever-teams/assets/107203576/1a5a011f-e1fc-41f6-affe-af177598af2a">

TES-13 task 25 (overrides 'TES-13 task 24')

<img width="1622" alt="Screenshot at Apr 29 16-45-33" src="https://github.com/ever-co/ever-teams/assets/107203576/a8285d94-bd66-41d1-a117-fa0e24a7261d">

**Expect**: if user enters name and clicks '+ Create Task' the system should create that task as new.

**Comment by evereq** [comment]
@paradoxe35 this is example of painful regression, I am pretty sure it was worked well before and was possible to create new tasks and select existed easy using main input... now it's not :(

**Comment by KostyaEver** [comment]
Just tried again, and it looks like working now as expected @paradoxe35 

CC: @evereq

**Comment by paradoxe35** [comment]
On my side too @KostyaEver
