### ISSUE TITLE
[Bug] Update changes right after 

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2456]
The issue is that after any changes the system updates all data only after refreshing the whole page.

When the user edits a task, renames, adds size, priority or any order action the page should display actual data right after the changes are made.

<img width="1618" alt="Screenshot at Apr 29 16-58-50" src="https://github.com/ever-co/ever-teams/assets/107203576/597b31e0-9d25-494b-b91a-bfca68fb7841">

<img width="1625" alt="Screenshot at Apr 29 16-59-45" src="https://github.com/ever-co/ever-teams/assets/107203576/250d24b5-3f3c-40be-b6cc-afddc06b424c">

<img width="1626" alt="Screenshot at Apr 29 17-01-20" src="https://github.com/ever-co/ever-teams/assets/107203576/cf3a52d0-d6ad-44d5-854b-88227278538b">

<img width="1617" alt="Screenshot at Apr 29 17-01-54" src="https://github.com/ever-co/ever-teams/assets/107203576/74c9a53c-475e-4d51-aec3-b16ce3a00cba">

**Comment by JoeMakuta** [comment]
Wanted to work on this but unfortunately, I can't find the behavior on the app anymore. @KostyaEver

**Comment by evereq** [comment]
@KostyaEver please check on latest app.ever.team and record a video this time if it still failing
CC: @JoeMakuta

**Comment by KostyaEver** [comment]
Looks like the issues auto-fixed (noticed that some other issues were auto-fixed as well) Someone fixed one issue which fixed all of these issues (it's good) hope it will not happen again.
@JoeMakuta 

cc: @evereq
