### ISSUE TITLE
[Feature] 'Plan's' views UI

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2468]
User should be able to view 'Plans' on User Profile page in different views

- ListView
- ColumnView
- TileView

**Comment by GloireMutaliko21** [comment]
@KostyaEver and @JoeMakuta, do we have any designs for these views ?

**Comment by KostyaEver** [comment]
@GloireMutaliko21 
we already have a ListView

So 'column' and 'tile' views would be nice to see the design.

The main purpose is to see compact and informative cards that are easy to use / read etc

**Comment by GloireMutaliko21** [comment]
Sir @evereq / @KostyaEver 
What if we have only the "Standard view" (i.e task cards view) and a calendar view ??? Why ? So we have the "Daily plans" that list all the tasks the user planned for a specific date. Make sens if the user can be able to see in a Calendar component (Which can have daily, weekly, monthly views, etc.) for what each date has the planned tasks inside.
