### ISSUE TITLE
[Feature] Member can't start Tracking time without Plan

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2471]
In Settings user should enable/disable such option 'Enforce Daily Plan' - on/off (switch)

1. By default, it should be Off, i.e. not required to have a Daily Plan to start work & time tracking!
2. so if the feature is ON If the system sees that the member does not have an 'Today' Plan, does not let him/her track time until the plan is added. 
3. so if the feature is ON, there is NO 'Planned work time' should force user to add in the popup 'Planned work hours'
4. so if the feature is ON, there are tasks without an Estimate, it should display a popup with planned tasks to provide estimates.

The '**Today's Plan**' should have the minimum:
- One task
- Task should be estimated
- Planned work time should be added

Note: we do NOT enforce for other days plans to provide estimates or planned work time, only the same day we enforce it.

if the system checks that the Plan meets minimal requirements, the member can start tracking time
<img width="799" alt="Screenshot at Apr 30 16-17-39" src="https://github.com/ever-co/ever-teams/assets/107203576/dd77792d-a9b2-45a6-973e-a1ddb2d7db62">

**Note**: add a tooltip 'Please, add a Today's Daily Plan to track time'

**Comment by GloireMutaliko21** [comment]
Sir @evereq, that setting should be a team or a personal member setting ?

**Comment by KostyaEver** [comment]
@GloireMutaliko21 it should be Team Settings
