### ISSUE TITLE
[Bug]: Error When SignIn with Email & Password

### ISSUE THREAD

**Issue by Cedric921** [ever-co/ever-teams#2488]
After Select Workspace and Team, When I click on `Continue` i get This Error
![Screenshot from 2024-05-04 14-50-29](https://github.com/ever-co/ever-teams/assets/83704005/0152a1c8-8ce1-439e-86e9-863dd90909ac)
<img width="563" alt="Screen Shot 2024-05-04 at 3 06 10 PM" src="https://github.com/ever-co/ever-teams/assets/83704005/6dd77e33-620d-49a0-a74e-76f4e546ea80">

**Comment by rahul-rocket** [comment]
@Cedric921 Seems things are working fine for me in Local.

https://www.loom.com/share/6a33b28834044732b84cfeec3c0ea327

**Comment by rahul-rocket** [comment]
@Cedric921 I got same issue on Live https://app.ever.team, but not API side its client side issue.
