### ISSUE TITLE
[Improvement] Task type | Remember the latest type of issue

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2496]
Once a user creates / changes a type of issue the system should always remember which type was the latest and suggest for new tasks the same.

Example: once the user created task 1 'Bug', when is about to create task 2 the type will be selected 'Bug' as well (the same behavior for all types) so that user can simply select/change to another one if needed

<img width="560" alt="Screenshot at May 06 08-50-14" src="https://github.com/ever-co/ever-teams/assets/107203576/18930cce-7684-433e-af0c-dc6b31f51ecf">

**Comment by evereq** [comment]
OK, so I think it should be a "Team" setting for each project that is called "DefaultTaskType" and we can add it in the Settings to mark one of the Task types as default. 

@JoeMakuta can you design and implement that? 

Thank you!
