### ISSUE TITLE
[Feature] Switch language

### ISSUE THREAD

**Issue by Anishali2** [ever-co/ever-teams#2526]
@evereq 
Sir, we are giving user the language switch option in settings page only but if we think about the user prospective so I think he needs to login first and there is no option in login page to switch language 
also mostly websites add this language translation switch in header or footer also in login signup page ?
I'm need your suggestion about this.

![image](https://github.com/ever-co/ever-teams/assets/105014311/cdaafb28-97cf-4dc4-84ef-a5753997bfce)

![image](https://github.com/ever-co/ever-teams/assets/105014311/538d5e00-89b9-4bc8-a892-18401077d181)

**Comment by evereq** [comment]
@Anishali2 we can add such a switch to 2 places:

1) when user logged in, we can add it to user menu below:

![image](https://github.com/ever-co/ever-teams/assets/118497/c428cce9-7acb-4d0a-bbbf-1830f63a8532)

2) when user logged in AND when user not logged in (e.g. login / register / other pages), we can add that switch to the footer, next to theme color switch (to the left of it)

![image](https://github.com/ever-co/ever-teams/assets/118497/f4ae20c5-57a2-4788-b359-555fdda38859)

![image](https://github.com/ever-co/ever-teams/assets/118497/246a2d2b-7901-4465-a025-74296886c103)

Let's make it look like at https://ever.team WIP website, see below:

![image](https://github.com/ever-co/ever-teams/assets/118497/d15c9931-f7e1-4701-928d-bd9ac7c51ec0)

**Comment by evereq** [comment]
@Anishali2 
1. Please add "flag" for countries into the dropdown, you can find many open-source libs with those flags images etc (please send a list of those popular libs you can find and we will decide which one to use).
2. I would like to still add that selector into user profile page - a lot of people never look into footer and also possible not all pages later will have that footer (especially after user logged in etc)
