### ISSUE TITLE
[Feature] Member Profile not found page

### ISSUE THREAD

**Issue by Anishali2** [ever-co/ever-teams#2544]
![image](https://github.com/ever-co/ever-teams/assets/105014311/88f731c4-cdb4-4cc4-97e1-568592dd823d)

**Comment by evereq** [comment]
@Anishali2 I don't know where you get that URL you try to open in screenshot, but looks like UUID of profile of person is cut off, i.e. it's not full UUID value...

**Comment by evereq** [comment]
@Anishali2 ah, you mean instead of that page we should show existed 404 page or what?

**Comment by evereq** [comment]
I think we can just show for now standard 404 page or you mean you suggest to create separate page for "Member not found"?

**Comment by evereq** [comment]
@Anishali2 , you can create it, yes and for now just use same design as for 404 page? And maybe write "Member Not Found" somewhere etc. Later on we can make dedicated design for such page (unless you see it in Figma already? In that case use it of course). @JoeMakuta can you make design for such a Member Not Found page in our Figma, unless it's exists there (based on our existed 404 page design please)?

**Comment by JoeMakuta** [comment]
_**Looks great !**_ :+1:
