### ISSUE TITLE
Captcha error when trying to register

### ISSUE THREAD

**Issue by barnabynagy** [ever-co/ever-teams#2582]
Self hosted ever install on railway.app What do I have to do to fix this?
![CleanShot 2024-06-04 at 18 42 07](https://github.com/ever-co/ever-teams/assets/650475/b3e46f38-82bf-4adb-ac15-2d62e90622e4)

**Comment by evereq** [comment]
closing as duplicate to https://github.com/ever-co/ever-teams/issues/1983
