### ISSUE TITLE
[Bug] Login pre-fill 'Code' inputs issue

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2598]
The issue happens when the user clicks
- log in with the magic link on the main page
- enter own email and confirm
- check email (see 'Code' and button 'Click here')
- clicking 'Click here, it opens login page with code inputs (looks like already tried to fill it - red notification)
- the issue is that code inputs are not pre-filled with code

Expect:
Once a user clicks on 'Click here' it should open the login page with pref-filled code inputs

Example
<img width="1595" alt="Screenshot at Jun 12 14-13-01" src="https://github.com/ever-co/ever-teams/assets/107203576/c38bac9d-3088-4ee8-906b-89933b97dcda">

<img width="729" alt="Screenshot at Jun 12 14-13-17" src="https://github.com/ever-co/ever-teams/assets/107203576/c983f406-3a23-4155-a607-f29592682e85">

**Comment by evereq** [comment]
Basically the link from email should open the page and prefill correctly code and simulate "Login" button click! I think we had it worked before, not sure what failed @GedeonTS
