### ISSUE TITLE
[Feature] 'Daily plan' | popup 'Planned work hours' logic

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2601]
The system should check if the user has a plan 'Today' or NOT

if the user has a plan and clicks 'track time' the system should display the popup 'Planned work hours' first and once the user provides planned time, then can start tracking the time.

**Important**: The system asks ONLY one time to go through this procedure (Add 'planned work hours' and 'provide estimates' that day)

User should be able two see two different popups in two cases
1. User has plan and all tasks have been estimated
2. User has plan and NOT all task have been estimated

<img width="489" alt="Screenshot at Jun 13 17-51-53" src="https://github.com/ever-co/ever-teams/assets/107203576/be0d8857-9e96-45e4-8546-920f23abd551">

The popup should have two inputs 'Hours' & 'Minutes' where the user just adds the approximate amount of planned work hours for today. (inputs should not have negative values)

The button 'Create Plan' should be renamed to 'Start working'
The title should also be renamed to 'Today's Plan'
The sub-title should be  'Add planned working hours'

<img width="410" alt="Screenshot at Jun 13 17-37-15" src="https://github.com/ever-co/ever-teams/assets/107203576/6ac30db6-9a17-4e33-a262-3e02c7a147ce">

Also if there are tasks with '0' estimates should also ask to add to the popup just with RED notification below that please add Estimates

<img width="810" alt="Screenshot at Jun 13 17-33-33" src="https://github.com/ever-co/ever-teams/assets/107203576/2775340c-4d3f-442a-90fb-a905dc3f7050">

Design needed - description of such popup here https://github.com/ever-co/ever-teams/issues/2603

**Comment by evereq** [comment]
@KostyaEver make sure this is not enforced on users, but a setting exists that allows to activate "require plan to track time" etc. I think we have a task for that already somewhere.

**Comment by KostyaEver** [comment]
Yes, here is the task https://github.com/ever-co/ever-teams/issues/2471
also updated the description @evereq 

@JoeMakuta
