### ISSUE TITLE
[Feature] Estimate planned task 'Enforce Daily Plan'

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2603]
During plan creation, it is not always convenient to force a user to provide estimates so that the user can plan tasks without estimation and planned work hours.

The main point is that if settings 'Enforce Daily Plan' is 'ON' or 'Off' (switch)

The system should track if 'Today' plan has even one task where the 'Estimate' field is '0'.

in such case should call a hybrid popup where the user can see a list of tasks and add 'planned work hours' two inputs

Shown list of tasks can be ONLY from planned for the day
_________________________________
Planned work hours
- Hours
- Minutes

Task (one record contains)
- task number
- task type
- task title
- hours (input)
- minutes (input)

Buttons
- 'Start working'
- 'Plan later'
_________________________________

<img width="410" alt="Screenshot at Jun 13 17-37-15" src="https://github.com/ever-co/ever-teams/assets/107203576/c0d7a4e2-b466-49e2-a336-acc6e06636bb">

'Note' on clicking the task title, it should open task description in a new tab

Provided estimates should override previous values of the task estimate.

Would be nice to design it first such hybrid popup

Important: it should enforce user only when in Settings is ON https://github.com/ever-co/ever-teams/issues/2471

Design one more variant with 'Notification' like described here
https://github.com/ever-co/ever-teams/issues/2614

**Comment by CREDO23** [comment]
This task is already done @Cedric921
