### ISSUE TITLE
[Task] Daily Plan | Sort by Dates

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2607]
Since 'Daily Plan' has a few tabs 'Today', 'Future', 'Past', it should distinguish 'Daily Plans' by dates

If tasks were planned in the Past date, they should be displayed in tab 'Past Tasks'

if tasks are planned in the Today, they should be displayed in tab 'Today's tasks'

if tasks are planned in Tomorrow or Some days, they should be in tab 'Future tasks'

so we clearly understand that under 'Today' is current date, under 'Tomorrow' is tomorrow's date.

So we need to make sure that today's plan for tomorrow will become 'Past Plan' and will be removed from tab 'Today'. but in 'Today' should appears that is in 'Tomorrow' and so on

<img width="1307" alt="Screenshot at Jun 12 18-00-37" src="https://github.com/ever-co/ever-teams/assets/107203576/d5b8d52d-c709-4e05-8880-ea86e6445594">

So Plans should migrate correctly within tabs

In each task details, we have block 'Daily Plans' where is who planned + date (it should help to move task to correct tab)

<img width="521" alt="Screenshot at Jun 12 18-10-58" src="https://github.com/ever-co/ever-teams/assets/107203576/1663a04a-9eb5-423c-bd45-8ad23800436f">

Here is an example of 'Daily Plan' that was created Yesterday, but it still displays as 'Today', and 'Tomorrow' it will also be 'Today'
<img width="1656" alt="Screenshot at Jun 13 10-17-47" src="https://github.com/ever-co/ever-teams/assets/107203576/1fe70133-ca18-4cc9-9be8-8b2ce8fd419b">

**Comment by Cedric921** [comment]
This task is already implemented 
@KostyaEver  / @evereq 

https://github.com/user-attachments/assets/34a82c78-5522-460e-bb38-ab0ef39a3f29
