### ISSUE TITLE
[Improvement] Settings 'Team' | Invited Members block

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2615]
Block 'Invited Members' should be collapsed if there is no one who is pending.

if there is one who is pending, it should display as uncollapsed

<img width="1563" alt="Screenshot at Jun 13 10-54-45" src="https://github.com/ever-co/ever-teams/assets/107203576/b3f8d296-cfab-4f8e-954c-a5b2b5262336">

**Comment by CREDO23** [comment]
@KostyaEver, I am working on this !
