### ISSUE TITLE
[Feature] 'Daily Plan' | When user has tasks in tab 'Outstanding' should get Notification

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2619]
Notification Should get any Role (Manager, Member etc) 

Notification should be on Top of the screen with the reference/button 'View' that leads to 'Outstanding' tab.

So we need to motivate users to complete uncompleted tasks as soon as they can.

The daily notification should be a solution for it (we should do this in settings how often notify)

User can close that notification, but every day once the user opens the app and still has tasks in 'Outstanding' should be able to see that Notification

Text: 'You have 'X' uncompleted tasks, please check in 'Outstanding'  'View' 'x''

<img width="776" alt="Screenshot at Jun 13 16-43-00" src="https://github.com/ever-co/ever-teams/assets/107203576/9f53b3a0-93b2-4bc8-b218-77e01b616421">
<img width="783" alt="Screenshot at Jun 13 16-42-49" src="https://github.com/ever-co/ever-teams/assets/107203576/701c4b8e-8862-4026-b25c-8d23a4854c5a">

**Comment by evereq** [comment]
@KostyaEver we can also add that "Stats" about qty of outstanding tasks and other metrics in some sort of "Dashboard" that will be visible for user after login to the platform.. We did not designed that page yet and show instead page with Team Tasks, but you may do it with @JoeMakuta already and design such Dashboard page. Which btw should show different things for Managers and Members! For Managers they should see more info about Team and a bit about themselves, while for Team Members they mostly interested to see own metrics and a bit of team metrics etc. Btw, good idea to also use concept of Widgets on such Dashboard page, like one we have in Gauzy now!
