### ISSUE TITLE
Settings menu / Personal - user should be able to use Danger Zone

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#262]
Settings menu contains

- Personal
- Team

In Personal

As a user, I should be able to use Danger Zone in order to delete my own account or log out everywhere

- 'Remove Account' button - user removes him/herself from all teams (Note: can't remove from a team if there is the only manager - first has to make another team member manager)
- 'Delete Account'  button - user fully deletes own account

Note: If a user has an account in Gauzy Platform should update data via API 

<img width="721" alt="Screenshot at Dec 14 15-08-35" src="https://user-images.githubusercontent.com/107203576/207616905-29873a7c-d51e-49be-97e6-57ad10e92cf9.png">

**Comment by KostyaEver** [comment]
@evereq I Tested the moment to delete my own account, seems like it deletes only from one 'workspace' because after deleting I was able to enter to another team with the same email.
AND it removes the account within only the same 'workspace'. 

Please, confirm that it is correct for now so that we can close the ticket

**Comment by KostyaEver** [comment]
@evereq please confirm that's above works for us ^

**Comment by evereq** [comment]
Yes, it's exactly how it should work: it's only removed user from one 'workspace' (and all teams inside of that workspace of course), not from all workspaces
