### ISSUE TITLE
[Task] Daily Plan | Plan tasks from tab 'Outstanding'

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2620]
When the user plans a task in the tab 'Outstanding', it should remove this task from the tab 'Outstanding'.

Additional info
The system should work on that moment that motivates users to complete as many as possible tasks that are uncompleted.
All such tasks will be added to tab 'Outstanding' automatically by the system and the system will notify about it daily.

Normally user should go to the tab 'Outstanding' and add to plans for other days.

The main goal is to keep 'Outstanding' empty.

Remember that if a task exists in 'Outstanding', it exists for a 'Daily Plan' in the past (currently)

**Comment by evereq** [comment]
> What do you think if we should keep a record of in which Plan the task was initially and in which Plan the task was completed? so kind of reference to the past to check. (the previous record should be like a trace with the latest condition - not an exact task)

@KostyaEver I am not sure it's that important... i.e. I can plan something for day X and move it to day Y plan and actually make it in day Z and don't really care about that "history" usually... more like Plan is just that - PLAN for some day, unrelated to how tickets get to it etc in most cases. So I would say - let's not worry above that "history" of movement of tasks between plans / outstanding etc. Task just moved from one place to another.

**Comment by KostyaEver** [comment]
it works as expected now
