### ISSUE TITLE
[Task] Daily Plan | 'Past Tasks'

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2622]
The tab 'Past Tasks' the same stats as 'Today'

<img width="1006" alt="Screenshot at Jun 13 17-03-13" src="https://github.com/ever-co/ever-teams/assets/107203576/fd38ba10-a819-4206-8cdd-42ca84bb6e9d">

User should NOT be able to EDIT 'Past Plan'

**Comment by evereq** [comment]
It also contradicts maybe with https://github.com/ever-co/ever-teams/issues/2621, where you say you want to display some different stats for different "tabs" etc... So essentially I think that's correct - we need to show different stats information, depending on location!

**Comment by CREDO23** [comment]
@evereq @KostyaEver what do you decide for this task?
