### ISSUE TITLE
[Task] Daily Plan | 'Outstanding' View mode (Dates, All) 

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2627]
There are two modes how user can see that 'Outstanding' tab

- Dates
- All

Dates - display per 'Daily Plan' (all tasks

All - display 'All' uncompleted tasks without relation to plans

<img width="1105" alt="Screenshot at Jun 13 17-10-58" src="https://github.com/ever-co/ever-teams/assets/107203576/2c9186f3-0765-4df2-a7b7-7b9a14a0d84d">

Dates
<img width="790" alt="Screenshot at Jun 13 17-27-24" src="https://github.com/ever-co/ever-teams/assets/107203576/a50c33fd-4817-4154-b858-ec94117a8dac">

All
<img width="841" alt="Screenshot at Jun 13 17-30-32" src="https://github.com/ever-co/ever-teams/assets/107203576/3fbaa838-c06b-4942-9187-2044d13059ed">

**Comment by Cedric921** [comment]
This Feature is already implemented 
@KostyaEver / @evereq 

https://github.com/user-attachments/assets/328028fe-461f-4d39-88e5-a32ec12bdf47
