### ISSUE TITLE
[Improvement] 'Daily Plan' | Notifications 'Remaining tasks' UI

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2668]
Fix content that is in the Notification

**Should be text: Text**: 'You have 'X' uncompleted tasks, please check in 'Outstanding' 

on the right part two buttons
- 'View' (open tab 'Daily Plan' tab 'Outstanding'
- 'X' (close notification

<img width="1660" alt="Screenshot at Jul 01 16-35-53" src="https://github.com/ever-co/ever-teams/assets/107203576/b6fe4108-42c6-4d65-8c3d-07b9eb2e5659">

**Comment by GloireMutaliko21** [comment]
Sir @evereq / @KostyaEver I already worked on same issue, exactly same feature and same description.
Please see :
- PR : https://github.com/ever-co/ever-teams/pull/2655
- Issue : https://github.com/ever-co/ever-teams/issues/2619

**Comment by evereq** [comment]
@KostyaEver can you check if its really same? If so, can we close this ticket??

**Comment by KostyaEver** [comment]
Could you see the difference? @GloireMutaliko21  
this
https://github.com/ever-co/ever-teams/issues/2619
and 2668


They are different because 'Feature' was in general implemented correctly with few mistakes and this task is aimed at fixing these mistakes [Improvement'

PS: not sure why but in most cases small details are missed always and I need to create similar tasks to fix them

CC @evereq

**Comment by evereq** [comment]
@KostyaEver can you write here what are diff exactly? Just a hint for devs, thanks! :)

**Comment by evereq** [comment]
And @GloireMutaliko21 after @KostyaEver explain, please work on this task to finalize this

**Comment by GloireMutaliko21** [comment]
@KostyaEver if it's about that short form difference, "You've" instead of "You have", Let's please close this ticket as I can fix it (less than 30 seconds) in the PR I'm working on now ...
CC: @evereq

**Comment by KostyaEver** [comment]
In the description all as it should be @GloireMutaliko21 

the main problem was that currently text ends on **'Outstanding View'** + button 'View' which looks really strange and not sure why it was added. 
Also if I am not mistaken when the user clicks the button 'View' it redirects to the wrong page, which should be logical to 'Outstanding'
