### ISSUE TITLE
[Improvement] 'Daily Plan' | 'Profile' page optimise space UI

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2670]
The issue is that for a user is NOT easy to navigate/see the list of tasks in the tabs Worked / Assigned / Unassigned / Daily Plan

There is not enough space.

It can be resolved by collapsing the top part of the page.

<img width="1668" alt="Screenshot at Jul 01 17-10-40" src="https://github.com/ever-co/ever-teams/assets/107203576/32c72632-947b-4e83-9ee4-69d1906d8324">

**Comment by KostyaEver** [comment]
looks like it duplicated functionality that was already implemented. 
No need to work on it

**Comment by GloireMutaliko21** [comment]
> looks like it duplicates functionality that was already implemented. No need to work on it

Sure ! I already worked on it

**Comment by evereq** [comment]
@KostyaEver so should we close ticket, I don't get it!?

**Comment by KostyaEver** [comment]
I close it @evereq
