### ISSUE TITLE
[Task] 'Daily Plan' | add 'Remove from all plans' option to Action menu

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2673]
Users should be able to remove plans from a specific day as well as from multiple days

For tasks that are planned for multiple days should be two options

- 'Remove from this plan'
- 'Remove from all plans' 

<img width="1602" alt="Screenshot at Jul 01 17-45-14" src="https://github.com/ever-co/ever-teams/assets/107203576/4a4e72b2-d37c-4565-8be3-dd268c92950d">

**Comment by Innocent-Akim** [comment]
Requesting the API for multiple Remove  @GloireMutaliko21

**Comment by GloireMutaliko21** [comment]
@ Innocent-Akim  I implemented API needs and FIT this task. You can
