### ISSUE TITLE
[Improvement] Login with one team/workspace

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2677]
The idea is when the user is a member of one team/workspace should skip step 'Select Team/Workspace'

<img width="683" alt="Screenshot at Jul 02 16-34-05" src="https://github.com/ever-co/ever-teams/assets/107203576/9883f55a-606a-4f33-9f93-6f73b6907cae">

Login without a password, just with the Magic link.

When clicks on the email button, it should NOT ask to select Only team or Workspace in case user is ONLY member of one Workspace and one Team.
It should open Team's page in the next tab

<img width="606" alt="Screenshot at Jul 02 16-30-43" src="https://github.com/ever-co/ever-teams/assets/107203576/45e1cac6-defb-46f1-b506-f4c338ae47fd">

**Comment by evereq** [comment]
Somehow we tried to do it many times and every time failed :)))) 
ONLY if there is one workspace and one team, basically we want to SKIP that selector and login user right away. 
I assigning to @GloireMutaliko21 as think he can finally make it work.
@GloireMutaliko21 please note there are a LOT of additional logic there on that page with selection of workspace / team, so please be careful to make sure you did not destroy existed logic. ONLY for case when it's one workspace / team we should add that code to bypass this selector page!
