### ISSUE TITLE
[Improvement] Pre-select the most recent Workspace & Team

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2678]
The idea is to have preselected the most recent used:

- Workspace
- Team

It may help avoid extra clicks for most users

<img width="683" alt="Screenshot at Jul 02 16-34-05" src="https://github.com/ever-co/ever-teams/assets/107203576/89daff60-1d21-49b9-86e5-52361063f908">

**Comment by evereq** [comment]
Yes, store it in browser localStorage or something like that OR even better if we have a settings for each Employee for "Default WorkspaceId" and "Default Team ID" and "Default ProjectId", 100% makes sense. Show what was selected before, but still require user to click "Continue"

**Comment by evereq** [comment]
@GloireMutaliko21 / @KostyaEver this is weird, because we kind of worked on similar in https://github.com/ever-co/ever-teams/pull/1839 before (by @desperado1802 ) and now I see similar tasks / code in https://github.com/ever-co/ever-teams/pull/2686, how is that possible!?

**Comment by evereq** [comment]
Ah, haha, he did it in mobile app :))) @GloireMutaliko21 / @KostyaEver ...

**Comment by evereq** [comment]
But still, it means @GloireMutaliko21 we already have that `defaultTeamId` in Gauzy APIs! (not sure about `defaultWorkspaceId`, don't think we have that for user in Gauzy, but please check!)
