### ISSUE TITLE
[Task] Soft 'Daily Plan' popup

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2680]
when the user just opened the application first time today https://github.com/ever-co/ever-teams/issues/2679 so can check 'Total worked time' is '0' then check below

the system checks
- Has Plan for today
- No Plan for today

**No Plan**

Should see an info popup 'Please create Plan for Today' button 'Create the Plaln'

Clicking on the button 'Create the Plan' should redirect 

- 'Daily Plan' tab 'Outstanding' ONLY if there are tasks
- Profile page and tab 'Assigned' to see all available tasks (if 'Outstanding' is empty)

**Note**: it is not necessary to create the plan, the user can simply ignore it and go to another page

**Important**: The popup should NOT appear on the same day anymore

**'Has Plan'**

Case 1: Today has plan and estimated all tasks

Should display a popup 'Add planned hours Today'  (if all tasks are estimated)

<img width="394" alt="Screenshot at Jul 16 11-07-50" src="https://github.com/user-attachments/assets/db33120b-51d7-4cbc-95f3-5a23b99c9406">

Case 2: Today has plan and NOT estimated even one task

Should see a popup 'Add Estimation' and 'Planned work hours'

<img width="509" alt="Screenshot at Jul 16 11-11-54" src="https://github.com/user-attachments/assets/1f07dc21-2f36-4255-be10-73057484f496">

**Important**:  instead of the 'Cancel' button should be 'Add Later' (that closes popup and user can do what even want)

related task https://github.com/ever-co/ever-teams/issues/2603

**Comment by KostyaEver** [comment]
So guys you always saying that it's done etc but in reallity you are missing information from description.

So if there is attempt to 'Start tracking' time with NO planned tasks, user can see popup and after clicking 'Ok' where it should redirect?

<img width="997" alt="Screenshot at Aug 09 17-35-39" src="https://github.com/user-attachments/assets/4f78c2ab-aa86-4734-8b7b-cbdc827ef111">

<img width="1623" alt="Screenshot at Aug 09 17-32-40" src="https://github.com/user-attachments/assets/75da58a3-27a9-4b73-ad40-98fd09724af6">


**Now it displays  'Today's Plan' that does NOT make any sense since there are NO planed tasks**


<img width="1620" alt="Screenshot at Aug 09 17-36-58" src="https://github.com/user-attachments/assets/18f6a084-e400-453e-b944-de705b345a24">


Please fix it and READ all the description to be sure that FLOW works as described @CREDO23

**Comment by CREDO23** [comment]
Hi @KostyaEver , the redirection works well, we should change just tabs I think! Today's plan - Assigned!

I would like to know if apart from the redirection you found something wrong in the popups logic!

**Comment by CREDO23** [comment]
Got it @KostyaEver
