### ISSUE TITLE
[Feature] Manual Time | 'Add manual time' popup/page

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2694]
The button should be placed on the Member Profile page and near the main Timer

The option should be related to members' permissions 
- Manual time tracking enabled/disabled (if disabled should not see button 'add manual time')

Clicking on 'Add manual time' should open a page/popup, where can
- select one date (default current day)
- Billable (true/false)
- select a start time (default 0:00 am, stats from 0:00 am to end time)
- select an end time (default current time, starts from 'start time ^ to current time)
- Badge displays 'How many hours added' (different between start/end added time)
- Team (preselected of current)
- Task selector (optional)
- Description: 'What worked on?'
- Reason (we may add dropdown with variants)

buttons
- View Timesheets
- Cancel
- Add time (confirm adding the time)

**Note**: it may require 'Time zone' selection because the team can be around the world (default should be current Team timezone)

<img width="339" alt="Screenshot at Jul 08 09-03-01" src="https://github.com/ever-co/ever-teams/assets/107203576/63c89692-e51c-4cd8-a685-5db429ed4353">

<img width="653" alt="Screenshot at Jul 08 09-19-27" src="https://github.com/ever-co/ever-teams/assets/107203576/a944d431-0fcb-49b5-8126-dba47ca746ac">

<img width="350" alt="Screenshot at Jul 08 09-03-34" src="https://github.com/ever-co/ever-teams/assets/107203576/b4cbc75a-819d-4182-bf2e-c3c37ba0778e">

Important: 'Add manual time' should be minimum in two places
1. Profile page
2. icon near the main timer

**Comment by evereq** [comment]
@KostyaEver can you add here screenshot from Ever Gauzy for the same popup?

**Comment by evereq** [comment]
@JoeMakuta can you please design this in Figma of Ever Teams? And next we will assign to developer to implement. Thank you!

**Comment by KostyaEver** [comment]
@JoeMakuta added examples, please see the description. For sure we need in new design all elements that are described in the text

cc: @evereq

**Comment by evereq** [comment]
@GedeonTS right after @JoeMakuta done with design in Figma, you can start to work on this task! Please make sure you are using all component libs we already have (e.g. shadcn, headless etc)

**Comment by JoeMakuta** [comment]
![Screenshot from 2024-07-10 13-54-03](https://github.com/ever-co/ever-teams/assets/96576539/21eaddd4-fd77-49b5-b9ce-4518c3845dc6)

@KostyaEver  @evereq

**Comment by KostyaEver** [comment]
@JoeMakuta maybe not so clear from description etc (less info bout design)

Please see that we need two types of Popups one like you show - the same size as Desktop time tracker
and another one kind of WEB variant should be bigger
Please first and second screens
