### ISSUE TITLE
[Bug] Kanban | Member's avatars

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2716]
On the header part, the user can see a list of project members with Avatars

Issue: When a user clicks, it leads to Member Profile, which is wrong.

**Expect**: Cliking on Avatar, the system should filter the whole Kanban page with ONLY tasks assigned to that member

<img width="939" alt="Screenshot at Jul 12 15-07-51" src="https://github.com/user-attachments/assets/c9933e60-3368-4bfe-8980-5181a907466a">

**Comment by KostyaEver** [comment]
It does NOT work as expected, not sure why the task was closed
@CREDO23 @evereq

**Comment by CREDO23** [comment]
Have you tested it in production ? 
We should make sure that my changes has been released in production !

Please a short loom of what I did [Loom[(https://www.loom.com/share/b9e78641578740acac60427dfb74feab?sid=1008eb08-3fed-42a5-ac18-7496722fd5ce)
