### ISSUE TITLE
[Fix] Auth passcode red error validation on loading

### ISSUE THREAD

**Issue by GloireMutaliko21** [ever-co/ever-teams#2726]
When the user tries to login with passcode on the page OR provides only email

<img width="1571" alt="Screenshot at Jul 16 09-23-30" src="https://github.com/user-attachments/assets/2376704e-733a-4871-ab8d-c4acad5d6316">

after entered his email and redirected to the passcode screen, the user should not see an error (Red shell inputs + text) for validation. The error must occur only when the user clicks on the "Login" button and the passcode length is wrong.

![passcode bug](https://github.com/user-attachments/assets/210ccd36-3814-4390-9455-8fd956b0c1d0)

Expect: Once user provided email, should see just page with no error. Should be time counter and inputs

**Comment by devansh-m12** [comment]
can i work on this issue ?

**Comment by evereq** [comment]
Yes @devansh-m12 if you would like to contribute, you are very welcome! We will ask our devs to stand by for a few days, let us know how it goes! :)

**Comment by KostyaEver** [comment]
Hi @devansh-m12 
I updated the description for more clearer idea of how to reproduce

**Comment by devansh-m12** [comment]
sorry @evereq i was late you can go ahead with @Anishali2 solution. I had different approch in mind but this also works.
