### ISSUE TITLE
[Fix] Login error on Empty Teams for the user

### ISSUE THREAD

**Issue by GloireMutaliko21** [ever-co/ever-teams#2733]
When the user login and does not have any team yet, we should display the home page asking him to create a new team.
The issue is that we get the error described on the below image.

![image](https://github.com/user-attachments/assets/9a292f5e-92e0-49dd-84e6-90d35dc76dab)

**Comment by CREDO23** [comment]
@GloireMutaliko21, what can I do to replicate this error ? Since when a user register, they start by creating a team ?

**Comment by GloireMutaliko21** [comment]
@CREDO23 after creating a new team, etc ... you can go to settings and delete/dispose your team. Then logout and try to log in again. There your account should be available but without any team...

**Comment by CREDO23** [comment]
@GloireMutaliko21 
I encountered some issue when reproducing the error:

1. Registration

When a user register, the reCAPTCHA is missing in development env (there is no a button for reCAPTCHA in dev), therefore I could not be able to create an account. However, I used the production app as a workaround to register ...

You can watch the scenario [here](https://www.loom.com/share/74bc027d3270468a9b92e54cd3eb01ef?sid=e5ac467d-5c42-4977-b3f5-7baeaaba293c)

2. I could not be able to log with email / password. Only passcode worked

In ever teams, there is no option to set password, so I used gauzy (logged in and set a password). Unfortunately, I could not log in ever teams with that password.

You can watch a scenario [here](https://www.loom.com/share/6ccb519808ad45408863856f28e4f57a?sid=b93390a2-686c-426d-80a3-22bf5c3a920d)
