### ISSUE TITLE
[Improvement]: All Teams UI for Manager

### ISSUE THREAD

**Issue by Cedric921** [ever-co/ever-teams#2742]
We need to make some improvements to "All teams" Page : 
- Fix the margin and spacing between cards in the "Teams" view.
- In the "Combine" view, 
    - Cards are not the same size when some employees have no active tasks.
    - The list of cards should fit the width of the page. If there are a lot of cards (team members), cards that don't fit should go to the next line.
 - The Filter Button looks Bad, it should have border, background... like primary or secondary Button 

https://github.com/user-attachments/assets/4964e446-2d6f-4306-95f8-02ede44139e8

**Comment by GloireMutaliko21** [comment]
@Cedric921 Can you also please display 'All Teams' in the Teams' dropdown on the page header when that page is active ??? ???
