### ISSUE TITLE
[Bug] Login | Ability to add 'Code' to Code inputs

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2746]
The issue is that user is not able to enter code that was 'Resend' to 'code' inputs

Steps to reproduce:

1. Enter 'Email' and click 'Continue'
2. Check email
3. Click 'Magic link' it opens new page
4. in case something went wrong, user is not able to remove prefilled 'Code'

Expect:

- User should be able to click on Code inputs and the system auto-highlight all Code inputs so that user can past or erase

<img width="835" alt="Screenshot at Jul 17 15-05-50" src="https://github.com/user-attachments/assets/f6694820-d7f3-485f-ab52-6310e4be982b">

**Comment by CREDO23** [comment]
@KostyaEver, give me a case where we would like to change something in the input code.
I am not able to reproduce the scenario ... !

**Comment by KostyaEver** [comment]
@CREDO23 please record a video of how you can not do it.

case simple, select 'login with the magic link', check email, and try NOT to click on the button, try to COPY a code and paste it to code inputs.

For me it ONLY replaces in the first input, we need to implement a way to past whole code to all inputs when click Ctrl+C / Ctrl+V of code. even it already has code in the inputs.

makes sense?

**Comment by CREDO23** [comment]
@KostyaEver, it works for me well ....

You can watch a record [here](https://www.loom.com/share/f5ba23b455ac442381695dbf078b1dc8?sid=be95f390-6d0a-459b-b0d2-fa61c715f791)

Actually, if something went wrong, you are redirected to the email input, then once fill the email input and click on the continue button, you will be redirected to an empty input codes so that you can past again .... I do not really understand your specific case...

**Comment by KostyaEver** [comment]
@CREDO23 could you try 'Ctrl + V' when there are NOT empty inputs

**Comment by CREDO23** [comment]
@KostyaEver, why not use the reset button just above if you want to past new code ?

![imageedit_3_3733877255](https://github.com/user-attachments/assets/d0106b4f-15ca-49c2-bbb8-56a65ad333b6)

**Comment by KostyaEver** [comment]
@CREDO23 button is a button, we can figure out how many more cases - the task about specific cases that we need to resolve.

User should simply 'Ctrl + C' and 'Ctrl + V' a lot of people do this way - I do very often.

Please let me know if it is still not clear
