### ISSUE TITLE
[Bug] UI | Section for members cards has no space scroll up/down

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2754]
The issue is that the user can not see all team members' cards.

The main page does not have space to scroll up/down - looks like it displays the whole page.

**Expect**: it should work as before 'Scroll up/down' of the whole page should be possible to see the Time tracker part and Members' cards section.

Members' cards section should ONLY see small scroll section when there is not space / small screen size.

<img width="1550" alt="Screenshot at Jul 18 08-36-27" src="https://github.com/user-attachments/assets/12b6d722-98bb-4a26-a22a-d71fe8401679">

**Comment by evereq** [comment]
This is wrong way to handle issue @KostyaEver , the real issue is that we added 2 messages that take a lot of space vertically etc. I will describe how it should be improved later
