### ISSUE TITLE
[Improvement] Estimate | '0' hours should display in different way

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2767]
The issue is that when the user provides an estimate of less than 1 hour, the estimate time section does not look nice (under the main card)

Variants:

- Display only 'Minutes' if there are '0' hours
- Display '0' hours without lines below
- Display empty section without lines below

**Important**: lines below should exist ONLY if BOTH inputs Hours & Minutes are empty, when ONE of them is filled, another one should NOT have the lines.

<img width="1524" alt="Screenshot at Jul 19 10-11-13" src="https://github.com/user-attachments/assets/43931d2b-f5c0-4886-b883-c3191445ce7e">

 @evereq please provide your vision which variant is more preferable

**Comment by CREDO23** [comment]
@evereq @KostyaEver 

What about this : [Loom](https://www.loom.com/share/795bfc7d37cc4ab3a720d1b85e222b49?sid=18764043-7b9b-4f7b-9369-cf76a45825d1)
