### ISSUE TITLE
[Improvement] Daily Plan | Delete Plan Button Tile View

### ISSUE THREAD

**Issue by Cedric921** [ever-co/ever-teams#2779]
Fix the delete Plan Button on Tile View, in Future and Past Tasks

<img width="1710" alt="Screenshot 2024-07-23 at 00 45 03" src="https://github.com/user-attachments/assets/8df478c7-6f86-4d0c-9f8b-96300986048e">

**Comment by CREDO23** [comment]
@Cedric921, the image in the description has not been uploaded successfully !
