### ISSUE TITLE
[Bug] 'Daily Plan' | The same task can be planned multiple times for the same day

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2837]
The issue is that a task can be planned for the same day/date multiple times.

**Expect**: the task can be planned ONLY once time a day, for sure task can be planned for multiple days

<img width="1592" alt="Screenshot at Aug 06 09-23-31" src="https://github.com/user-attachments/assets/f639885c-8e12-4ac9-ab32-c87710f3b2f0">

<img width="1579" alt="Screenshot at Aug 06 09-24-22" src="https://github.com/user-attachments/assets/1f2f6483-0912-4e31-8b64-27b8adcdb0a0">

**Comment by CREDO23** [comment]
This bug is already fixed @KostyaEver , please close this !

**Comment by KostyaEver** [comment]
looks like it works, closing
