### ISSUE TITLE
[Bug] 'Daily Plan' | unexpected Popup is popping up

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2849]
The bug randomly happens when the user is trying to go back to the main page from the profile page

Case how it might be reproduced:
- Add task to 'Today plan'
- Click 'Back'
- the popup should appear (that should NOT happen in such case)

**Expect**: popup should not appear when the user clicks 'Back' (or the profile page) button

<img width="1592" alt="Screenshot at Aug 07 09-38-58" src="https://github.com/user-attachments/assets/549cf790-f010-49b4-8acf-08e05c55943c">

What appears as the result
<img width="1548" alt="Screenshot at Aug 07 09-38-27" src="https://github.com/user-attachments/assets/6de1f484-5060-456d-88b4-9fcbb27fb560">

**Comment by KostyaEver** [comment]
I see it is not merged still, please @evereq merge it (if issue was fixed) very annoying bug.

Just notice that 100% of the popup appears when 

- The user did not have a Plan
- on OWN Profile page, the user added to the Plan (one or more tasks)
- click 'Dashboard page' (the main page)
- the popup appears

please double check that this case is also fixed @CREDO23

**Comment by CREDO23** [comment]
In that case this poopup should appears (one time per day in SOFT FLOW) !
Or if I am wrong , when do you want this popup to appear ? @KostyaEver

**Comment by CREDO23** [comment]
> I see it is not merged still, please @evereq merge it (if issue was fixed) very annoying bug.
> 
> Just notice that 100% of the popup appears when
> 
> * The user did not have a Plan
> * on OWN Profile page, the user added to the Plan (one or more tasks)
> * click 'Dashboard page' (the main page)
> * the popup appears
> 
> please double check that this case is also fixed @CREDO23

In that case this poopup should appears (one time per day in SOFT FLOW) !
Or if I am wrong , when do you want this popup to appear ? @KostyaEver

**Comment by CREDO23** [comment]
Just to make sure, when do you want this popup to appear ? @KostyaEver

**Comment by KostyaEver** [comment]
it is an incorrect question @CREDO23  - make sure that it does NOT appear according to the description.

When should appear we already have separate tasks that are in TODO or already DONE
