### ISSUE TITLE
[Feature] 'Planned' | extent 'Action (...) Manu' with 'See Plan'

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2891]
The main purpose of the feature is to add the ability to see Plans on demand if the user wants to check without going to the Profile page - tab 'Planned', the user can see all in a popup on the main page 'Dashboard'.

The option should be available per user
Everybody can see the plans of all team members, only managers can manage the plans of others and see controls on the popup

Add
- Divider 'line' between what is already in Action ( ... ) menu
- Add option 'See Plan' below the 'Divider'

<img width="1613" alt="Screenshot at Aug 14 08-51-44" src="https://github.com/user-attachments/assets/0e309169-333f-4705-a95b-5fb96bc5ee72">

**Comment by CREDO23** [comment]
@KostyaEver I need the design of that popup, so I can work on this task !

**Comment by KostyaEver** [comment]
@CREDO23 That's why I did not assign the task because we don't have a design

**Comment by KostyaEver** [comment]
@CREDO23 you can add this action 'See Plan' and see popup with tabs https://github.com/ever-co/ever-teams/issues/2892
