### ISSUE TITLE
[Task] 'Planned' | View popup 'Planned'

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2892]
This new popup should exist for v.1 when the user clicks 'See Plan'

The popup should be unified for all plans, at the header 3 tabs 'Today' / 'Tomorrow' / 'Future' (in v.1 we display only Current and Future plans)

if user clicks on the tab 'Today' or 'Tomorrow', it should display what the user can see on the popup (add planned time, list of tasks + estimates AND below information if there is something that needs to be fixed etc)

if clicking 'Future' opens 'Calendar' where the user can see planned days, by clicking on the planned day can see the same view as for 'Today' or 'Tomorrow' just the name of the tab is a date in the format 'DD.MM.YEAR'

**Note**: the Calendar should fit to the defined popup size without changes
Once the user selects a date can see a list of tasks, instead of tab 'Future' the user can see the 'Date' and somewhere above should be **Arrow '<-' back** which means go back to the 'Calendar' and select another date if needed. (or simply click on tab 'Today' or 'Tomorrow')

The button 'Start working' should be visible in the tab 'Today', in other tabs should be 'Edit plan' buttons

<img width="424" alt="Screenshot at Aug 28 08-47-25" src="https://github.com/user-attachments/assets/84ad4684-6358-487f-851a-9d707aaab2d1">

<img width="412" alt="Screenshot at Aug 28 08-48-13" src="https://github.com/user-attachments/assets/f42229fe-1a70-45a2-ab7e-f2894d640ac1">

Above columns 'Estimations' add 'Total Estimation' that should calculate all tasks time so that user can see

if there are tasks without estimations they should be sorted at the top of the list so that user can estimate quickly, without searching.

**Important**: Text below the table that gives an understanding of what is wrong with a selected plan should display actual information about the selected plan.

Example:

1. There are tasks that are not estimated:
Should be red text that 'Please estimate all tasks'

2. There are no 'Planned' work hours'
Should be red text that 'Please add planned time'

3. There is a bit of difference in 'Planned time' and 'Total Estimates' (allowed +/- 1 hour) ('Total Estimates' **less** than 'Planned time')
Should be red text that 'Please add more tasks to the plan'

4. There is a bit of difference in 'Planned time' and 'Total Estimates' (allowed +/- 1 hour) ('Total Estimates' **more** than 'Planned time')
Should be red text that 'Total estimated time exceeds your Planned time, please optimize your plan'

**Comment by CREDO23** [comment]
Hi @KostyaEver, when should this popup be displayed ?

**Comment by CREDO23** [comment]
I would suggest some improvements:
- When there is no planned tasks for tomorrow / future, we can either:
  - Show a message : "There is no task planned"
  - Disable the Tomorrow / Future button"
- For the case where there is a bit of difference in 'Planned time' and 'Total Estimates' (allowed +/- 1 hour) ('Total Estimates' less than 'Planned time'), the text  'Please add more tasks to the plan' should be clickable and when the user click on it, s/he will be redirected to Profile / Assigned tasks

**Comment by CREDO23** [comment]
> Let's NOT change the logic before we implement the popup. @CREDO23 Please during implementation fully ignore your last comment @CREDO23
> 
> When we display the popup - task here #2891

OK @KostyaEver, waiting for the popup design !
