### ISSUE TITLE
[Task] 'Planned' | Logic 'Planned popup' issue

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2895]
The issue is in SOFT mode when the system displays 'Planned popup' an the user clicks 'Start working' the system starts tracking time on the selected task (which is not planned actually)

There are a few ways

1. if on the Dashboard, the selected task (user card) is planned today, then after clicking 'Start tracking' should open the popup 'Planned tasks' (even everything was provided before, including estimates, planned working time and so on)

2. if on the Dashboard, the selected task is not planned today, then after clicking 'Start tracking', first it should ask the user additionally in a popup :
- Would you like to add the task 'task # number' to Today's plan?  
- Button 'Yes', it adds task to Today's plan and system is tracking time on this task
- Button 'No', it does not add the tasks to any plan, and system is tracking time for selected task (ignoring Today's plan)

<img width="283" alt="Screenshot at Aug 19 09-59-26" src="https://github.com/user-attachments/assets/2a69139f-7ed0-4c4f-a2ac-06b041b8980d">

second, right after user adds or not the selected task, should see the popup 'Planned tasks'

Another way to continue tracking time for selected tasks is by clicking 'Cancel' or 'X' on 'Planned tasks' popup (like ignore it)

**Note**: it should work ONLY for SOFT mode that is ON in Settings 

Example, where user can see described buttons of 'Planned tasks' popup

<img width="442" alt="Screenshot at Aug 14 10-19-41" src="https://github.com/user-attachments/assets/77f13387-23f9-4175-ba63-20983918a62f">

**Comment by CREDO23** [comment]
I have already implemented a popup to enforce user to work on a planned task (when Require a plan to track is ON), I think we can reuse that popup for this task @KostyaEver 
![Screenshot from 2024-08-14 19-23-03](https://github.com/user-attachments/assets/6206fc04-799b-4d38-808b-922907d8d61d)

**Comment by KostyaEver** [comment]
@CREDO23 yes, we can use this popup, just make sure that content and logic as described above
