### ISSUE TITLE
[Design][Improvement] 'Planned' | User should be able to add/remove tasks from/to the popup

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2938]
WE NEED TO DESIGN IT FIRST then we can implement

The issue is that currently user is not able to ADD / REMOVE task(s) within the planned popup.

if a user sees the popup, should be able
- Add task(s)
- Remove task(s)
- Edit estimate (in case it was provided)
- View (it will open task description - or preview so that the user can understand task better)

1. 'Add task(s) should be able by clicking button [ + ]  near the list of planned tasks

Clicking on the [ + ] instead of the list of planned tasks should open a list of tasks (Assigned) and at the top of the list should be a search input, that the user can search and start typing and it shows appropriate tasks.
Next to each task should be small button 'plan'

2. 'Remove' from the plan should be added 'Action (...) menu with value 'Unplan'

So when user clicks on it, the system should remove selected task from that plan

Note: Action (...) menu should be added at the end of task card right after estimate

3. 'Edit estimate', the user should be able to change/add an estimate to the task (as the same logic currently works on the main page), Add option 'Edit' to the Action ( ... ) menu as well

**Important**: by default all tasks without estimation should be in EDIT mode so that the user can easily add digits into the hours/minutes inputs. ONLY if estimate was provided those card should NOT be in EDIT mode.

4. 'View' we need to decide either open full tasks details or open task description preview in small popup???

**Comment by Cedric921** [comment]
@CREDO23  you will work on this task when design will be ready

**Comment by KostyaEver** [comment]
@Cedric921 @CREDO23 
it was already implemented, not sure why we need design

**Comment by CREDO23** [comment]
This issue can be closed @KostyaEver
