### ISSUE TITLE
[Improvement] 'Settings' | adapt sub-menus of 'Team' & 'Personal' menus UI

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#3013]
The issue is that the sub-menus (in RED) looks almost the same as the main menus which makes a user confused.

![Screenshot at Sep 10 09-36-36](https://github.com/user-attachments/assets/695514a5-09c2-4d6a-8c39-a3df9d4c3e88)

There are a few improvements:

1. if both menus 'Team' & 'Personal' are uncollapsed, should have the same background color (currently only one menu has it)

<img width="293" alt="Screenshot at Sep 11 08-02-50" src="https://github.com/user-attachments/assets/bf74cf9d-114e-4987-a12e-7643bf7a7b04">

2. All Sub-menu titles should start a bit right, it should give the feeling that they are sub-menus and nested under the main menu

<img width="300" alt="Screenshot at Sep 11 08-06-19" src="https://github.com/user-attachments/assets/352dfb27-70e3-4710-a9dc-300f0989d7b9">

3. Color of the background of the sub-menus (like in the first screen area) should be 'Grey' not back (at list we can try to see how it looks)

**Comment by land-bit** [comment]
Hi @KostyaEver and @CREDO23 , I'd like to contribute to this project by resolving this issue if I may.

**Comment by evereq** [comment]
@CREDO23 you did not start yet working on this?

**Comment by evereq** [comment]
@land-bit you can do it now, thank you for willing to contribute!
CC: @CREDO23 skip this task

**Comment by land-bit** [comment]
Hello @KostyaEver , I am working on this issue but I can not understand the 3rd point, could you please explain?

I understand that you'd like to try changing the sub-menu backgrounds to "Grey" as in the first area of the screen, could you show me this area?
