### ISSUE TITLE
[Improvement] 'See Plan' | ability to add task to Empty plan

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#3028]
The issue is that when the user clicks 'See Plan' and there is NO plan for tabs 'Today' & 'Tomorrow', there is no ability to create a Plan (add tasks)

**Expect**: When there are no tasks, the user should see 
- input 'Add planned working hours' 
- button [ + ] 'Add tasks'

<img width="553" alt="Screenshot at Sep 17 08-23-00" src="https://github.com/user-attachments/assets/082e1bc8-88d0-4b86-baed-bfb325d6a4ad">

Simply add two elements to the Empty popup tabs 'Today & Tomorrow'

So this way users can create plans as well

<img width="599" alt="Screenshot at Sep 17 08-23-22" src="https://github.com/user-attachments/assets/eb676a8e-fbcd-4fd2-8678-7600b2d3caee">

**Comment by land-bit** [comment]
Hello @KostyaEver and @CREDO23! Do you mind if I resolve this issue?

**Comment by CREDO23** [comment]
go on please @land-bit

**Comment by KostyaEver** [comment]
clicking button [ + ] cause exception @CREDO23
