### ISSUE TITLE
[Bug] The app exception appears while navigating the app

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#3054]
When user logged in in 20-40 sec meanwhile user is using the app it gets exception

<img width="778" alt="Screenshot at Sep 20 09-18-44" src="https://github.com/user-attachments/assets/cd8e49a9-5b92-451e-9ac3-67557de3e4ec">

**Comment by KostyaEver** [comment]
Guys, the issue has not been fixed. I reopen @CREDO23 

cc @evereq

**Comment by CREDO23** [comment]
Changes are not released in production yet @KostyaEver
