### ISSUE TITLE
[Improvement] 'See Plan' | Dropdowns 'Months' & 'Years'

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#3062]
The issue is that the user can see all months or years by clicking ONLY the 'arrow down'
AND
the most annoying is that when clicking on the area a bit left/right - fully closes whole popup

Expect: 
1. The user should be able to see an opened dropdown when clicking on the whole RED areas around 'Months' & 'Years'
2. When user clicks a bit out of dropdowns, it should NOT close the whole popup

<img width="620" alt="Screenshot at Sep 24 08-47-55" src="https://github.com/user-attachments/assets/e104931a-11c6-489e-8a98-5d2c20af1a82">

**Comment by KostyaEver** [comment]
@CREDO23 please make sure that if the plan existed in 2023, it will show that year as well, because I can not test it

<img width="575" alt="Screenshot at Oct 03 11-25-17" src="https://github.com/user-attachments/assets/7d839ebc-93dd-4c5a-b177-47d92d5491d2">

**Comment by CREDO23** [comment]
sure @KostyaEver
