### ISSUE TITLE
[Improvement] 'See Plan' | How open date in the Calendar

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#3063]
The issue is that to See the Plan in the Calendar, a user should select a Date and click the button 'Select' it shows a Plan for the specific Date

**Expect**: Additionally the user should be able to double-click on specific dates and see a Plan

as a result there are two option how to open any Plan on the Calendar

<img width="634" alt="Screenshot at Sep 24 08-57-17" src="https://github.com/user-attachments/assets/33d279d8-0840-493a-87a9-bfc5557e5007">

**Comment by CREDO23** [comment]
@KostyaEver, unfortunately, the package we are using for calendars does not support the double click event yet
