### ISSUE TITLE
[Fix] Settings | Icon direction when sections are collapsed / expended

### ISSUE THREAD

**Issue by CREDO23** [ever-co/ever-teams#3080]
The issue is that: the icon position is reversed

[Screencast from 2024-09-27 10-28-31.webm](https://github.com/user-attachments/assets/c12cc34f-07b7-4a0f-9d76-0bbde872037e)

It should be:
- **Down** when collapsed
- **Up** when expended

**Comment by land-bit** [comment]
Hello @evereq and @CREDO23, I'm picking up the issue
