### ISSUE TITLE
[Feature] Task | Create new project in Add Task or Task Detail page

### ISSUE THREAD

**Issue by ariefgp** [ever-co/ever-teams#3101]
**Related Document:** 
- [Document 1](https://www.notion.so/everco/As-a-team-member-I-want-to-create-a-new-project-directly-from-the-task-add-edit-form-when-the-proje-114dfdd17ffd80429791e5d1c72c9146?pvs=4)
- [Document 2](https://www.notion.so/everco/As-a-team-member-with-the-Users-Team-Members-permissions-I-should-be-able-to-add-tasks-in-the-proje-10ddfdd17ffd80509759d061377c98e2)

**Related issues:**
- #3098
- #3099 
- #3100 

---

As a team member, I want to create a new project directly from the task add/edit form when the project I need isn't listed, so I can efficiently categorize my task without interrupting my workflow.

**Detailed Flow:**
1. User is in the process of adding or editing a task
2. User clicks on the project dropdown
3. User scans the list but doesn't find the desired project
4. User selects add button at the bottom of the dropdown
5. System opens a quick project creation modal
6. User enters essential project details (project name and color)
7. User submits the new project information
8. System creates the new project and adds it to the user's project list
9. The project dropdown updates, showing the newly created project as selected
10. User continues with task creation/editing

**Acceptance Criteria:**
1. Project Dropdown:
    * An add button is clearly visible in the project dropdown
    * This option is typically placed at the bottom of the project list
2. Quick Project Creation:
    * Selecting add button opens a modal
    * The form includes fields for essential project information 
3. User Experience:
    * The project creation process is quick and doesn't navigate away from the task add/edit page
    * Form for new project is simple and doesn't require extensive information to create
4. Project Creation and Selection:
    * Upon successful creation, the new project is immediately available in the dropdown
    * The newly created project is automatically selected for the current task
    
**Additional Information:**
<img width="1489" alt="image" src="https://github.com/user-attachments/assets/024ed7fc-7013-4eec-a5df-cc1f6a81afad">

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/2343a0a6-5b86-4456-8f06-844e6a0a2f50">
Add project should have similat button like this

<img width="1417" alt="image" src="https://github.com/user-attachments/assets/34fda221-6b57-4a49-8af8-fc4ee44afb57">
Show a modal like this when creating new project

**Comment by KostyaEver** [comment]
<img width="864" alt="Screenshot at Oct 03 09-08-52" src="https://github.com/user-attachments/assets/3a75560d-b578-495d-8223-1336ba3fbd89">

@ariefgp

**Comment by KostyaEver** [comment]
<img width="1480" alt="Screenshot at Oct 03 10-04-33" src="https://github.com/user-attachments/assets/31e6ea1f-cd32-4e36-b22d-745e93b1afcc">
