### ISSUE TITLE
[Feature] Vertical Sidebar | Role-Based Navigation in Sidebar

### ISSUE THREAD

**Issue by ariefgp** [ever-co/ever-teams#3104]
## Related Document
- [Document 1](https://www.notion.so/everco/As-a-user-I-want-to-see-navigation-items-relevant-to-my-role-in-the-sidebar-so-I-can-access-featur-114dfdd17ffd80378f80c996536c38a9?pvs=4)
- [Document 2](https://www.notion.so/everco/As-a-user-I-should-be-able-to-navigate-using-the-vertical-nav-bar-2fa730dff2e6485b8a4af6e184d24a95?pvs=4)

## Related issues
- #3102
- #3105 
- #3106 
- #3107 
- #3108 

---

**As a user, I want to see navigation items relevant to my role in the sidebar, so I can access features I have permission for.**

## Detailed Flow
1. User logs into the Ever Team platform
2. System retrieves user's role and permissions
3. System generates sidebar navigation based on user's permissions
4. Sidebar displays only the items and sub-items the user has access to
5. If user's role changes, sidebar updates dynamically upon next login or refresh

## Wireframe
![image](https://github.com/user-attachments/assets/a21ad218-26bc-4f1d-98e4-0b7c0c6fd22c)

## Acceptance Criteria
* Sidebar only displays items and sub-items the user has permission to access
* There are no visible gaps or indicators of hidden items the user doesn't have access to
* The sidebar structure remains consistent despite hidden items
* Sidebar updates dynamically if user permissions change (may require refresh)
* Attempting to access restricted areas via URL results in appropriate error message

**Comment by KostyaEver** [comment]
@ariefgp would be nice to see what exactly should be on the Nav bar for each role. 
please, list all menus per role (otherwise nobody guess)
cc @karenever

**Comment by ariefgp** [comment]
From me it should be:
Team Manager : All menus
Team Members: Exclude reports
Wdyt @karenever ?
