### ISSUE TITLE
[Bug] Common | Public link URL does not work

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#3126]
The issue is that the public link does not work

<img width="1401" alt="Screenshot at Oct 04 18-16-35" src="https://github.com/user-attachments/assets/f94f53aa-9044-4a4c-aaf6-2037b350bcce">

Steps to reproduce

1. Go Settings
2. Copy 'Public link' URL
3. Past to another Browser or Incognito
4. Should Open Public VIEW of team for any user (instead it opened Login page)

**Comment by evereq** [comment]
@paradoxe35 we need your help with this one, it was already build I think, but we need to check why its not work anymore... maybe when we change routing from page to app etc. Please do this fix as priority.

**Comment by paradoxe35** [comment]
Okay @evereq

**Comment by KostyaEver** [comment]
I've fixed it a minimum 2-3 times already @evereq 

Hope, it is final

cc @paradoxe35
