### ISSUE TITLE
[Bugs] Daily Plan | Change positioning of “Delete this plan” button

### ISSUE THREAD

**Issue by ariefgp** [ever-co/ever-teams#3127]
More detail document: [Document](https://www.notion.so/everco/Change-positioning-of-Delete-this-plan-button-113dfdd17ffd80cbaf72ef837dd1491e)

- In Daily plan, the position of the delete button has some issues. When a user adds multiple tasks:
    - under cards view, it goes all the way to the bottom so the user has to scroll to the end to find it.
    - under table view, it’s down at the bottom
    - under blocks view, it’s distorted.  
    
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/b627966a-e9d8-4682-851c-5071f3bed83f">

- Reposition the button like below
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/f064b169-2d35-43bc-a403-16193d31da6d">

**Comment by Tacite243** [comment]
Hello Thierry, I would like to fix this issue, can you assign it to me?
