### ISSUE TITLE
[Improvement] Create Task | Assign another team member on create new task

### ISSUE THREAD

**Issue by ariefgp** [ever-co/ever-teams#3130]
More detail document: [Document](https://www.notion.so/everco/Add-assignee-to-create-task-1c2d07c5c19745fca6294101ccbf9539)

# Summary

- It is not currently possible to assign a task to some other member while creating a task. The system automatically does self-assignment by default. For task assignment to be done, the user has to navigate to already created tasks to change the assignment. 
- We can add option to select assignee/team member for the task here
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/8fe631a6-c457-48a2-a907-d1cc69e552fc">

**Comment by evereq** [comment]
Yes, makes sense, we can show there a component to select other team members (multi-select) and assign those to the task. That component can also display currently logged in user as a default selected item (because task will be assigned automatically to that member).
