### ISSUE TITLE
Settings menu / Personal - user should be able to set/change Avatar

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#377]
Settings menu contains

- Personal
- Team

In Personal

As a user, I should be able to set/change own Avatar

<img width="631" alt="Screenshot at Dec 15 14-09-55" src="https://user-images.githubusercontent.com/107203576/207867359-80e33159-a820-4585-94d9-6813e2efa7ea.png">

**Comment by KostyaEver** [comment]
Does not work for me.
Make sure that it crops the photo to an appropriate size no more that XX mb
@Sergemuhundu

**Comment by desperado1802** [comment]
Proof that issue is resolved:
https://github.com/ever-co/ever-teams/assets/124465103/d54e954d-2cb8-472c-b2d6-3121a7e5b039
