### ISSUE TITLE
Settings menu / Team - user should be able to set/change team Logo

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#383]
Settings menu contains

- Personal
- Team

In Team

As a user, I should be able to set/change own team Logo (available for managers)

<img width="197" alt="Screenshot at Dec 15 14-05-51" src="https://user-images.githubusercontent.com/107203576/207866832-8db5bbcc-b1fb-4d18-a8df-9c28e1fc6018.png">

**Comment by desperado1802** [comment]
Proof that issue is resolved:

https://github.com/ever-co/ever-teams/assets/124465103/3a1c2694-e748-4394-bf00-182500a564ad
