### ISSUE TITLE
Task page - Side panel / Issue Privacy

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#504]
An issue should have two types
- Public (default)
- Private

<img width="298" alt="Screenshot at Feb 10 12-57-17" src="https://user-images.githubusercontent.com/107203576/218086983-c91ff980-0238-42f4-b3d2-ebe1c349b186.png">

**Note**: the option set Privacy will be Disabled - if in the settings set an option to make 'the privacy of all Child issues the same as Parent (Epic)' -

**Comment by evereq** [comment]
I think this is done already and should be working, closing it.
