### ISSUE TITLE
Task page - Side panel | Estimate block

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#509]
An Issue should have an Estimate block, where Team members can estimate the issue 

- in Hours & Minutes
- in Story Points

**Note**: it depends on what is set in Team Settings by Manager

- 'Icon' settings next to 'Estimate' (activates mode to exclude/include any Assignee estimate)
- Estimate (Common - average)

_user element_
- Avatar (Assignee's)
- Full Name (Assignee's)
- Estimate (Assignee) OR two inputs for Hours & Minutes (depends on current condition)
- '+' & '-' buttons (in settings mode: next to each Assignee in order to include or exclude estimation)
**Note:** if a user is willing to change the estimate - should be able to click on it two times and it should display the current estimate in EDIT with two inputs.
**Important**: Assignees who have to provide Estimates MUST NOT see the average and estimates of others until they provide their own. Once they provided an estimate can see ONLY the Average Estimate. ONLY Managers can see Estimates of other Assignees and Average

- ... (more Assignees)
- 'Add member' button (open list of members who should estimate) (some members can be added automatically by the system)

**Note:** Excluded Assignee is displayed in Grey color and next to '+' button to include estimate again (It visible to managers only, for all others it display as normal set of estimates and so on)

It displays the average estimated time by all responsible Assignees and per each assignee.

<img width="289" alt="Screenshot at Feb 10 14-47-27" src="https://user-images.githubusercontent.com/107203576/218108064-5106891c-8146-44f8-af3a-dce6b6e7e4a7.png">

<img width="287" alt="Screenshot at Feb 10 14-47-48" src="https://user-images.githubusercontent.com/107203576/218108078-309e4fbf-1efd-4867-a470-500576ecdb28.png">

**Comment by badalkhatri0924** [comment]
We have 2 ways to handle Task Estimation:

**Approach 1:** 
Ones someone edited task estimate DIRECTLY, we do not override it anymore with suggestions (but we DISPLAY suggested estimate next to current one in UI). So basically before someone define estimate for task itself, we use "suggested average", but after someone estimated task itself specifically (person who start working on it), we keep that value and only can display what other suggesting, but it will not effect current estimate (Will implement in future)

**Approach 2:** 
Ones someone edited suggested estimate (or new suggested estimate added by someone or existed suggested estimate removed), we always recalculate task estimate and override that value in DB (estimate field) (Will implement in V1)
