### ISSUE TITLE
Task page - Linked Issues block

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#521]
An Issue should have Linked Issue blocks (under the Description block), 
where are listed 
- Child Issues (of the current issue)
- Related Issues (of the current issue)

Users can add Children and Related Issues to the Current Issue by clicking '+' button which calls Pop with Issues

<img width="586" alt="Screenshot at Feb 13 12-20-15" src="https://user-images.githubusercontent.com/107203576/218448091-b7b34011-ac8f-489c-97e6-69f682916b5b.png">

**Comment by main95** [comment]
Hi, @KostyaEver, i'm new in the project, can I take this issue?

**Comment by evereq** [comment]
Hey @main95 , thank you for offering help with our project! This task actually depends on functionality of our Gauzy APIs, which I don't think is done at this stage, so this task can't proceed. If you have time to help our project(s) development we can discuss what task is a good to start etc. Let me know if it's interesting for you.

**Comment by main95** [comment]
Hi @evereq, yes I'm interesting in help to yours projects, I'm finding some side projects in my web dev career, do you have some infos?

**Comment by evereq** [comment]
@KostyaEver and me will check what tasks we can delegate @main95 , we will message you next week (having holidays now)

**Comment by main95** [comment]
ok, thanks

**Comment by badalkhatri0924** [comment]
@paradoxe35 

Child Issue/task related API changes are done.

In GET API you need to pass `children` and `parent` relation.

We have introduced new `parentId` field. you can add logic in update API to handle this task.
