### ISSUE TITLE
Settings Checklist - Readiness

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#612]
**Settings** Mark which is done

**Personal**

- [x] Avatar #377 
- [x] Full Name #376 
- [x] Contacts (Email, Phone) #374 
- [x] Themes #375 
- [x] Language #372
- [x] Timezone #373 
- [x] Remove Account #378 
- [x] Delete Account #378 

**Team**

- [x] Logo #383 
- [x] Team Name 
- [x] Tracking Time #381 
- [x] Task Statuses #380 
- [x] Task Priorities #380 
- [x] Task Sizes #380 
- [x] Task Labels #380 
- [x] Transfer Ownership #382 
- [x] Remove Team #382 
- [x] Quit Team #382

**Comment by desperado1802** [comment]
Closing as all the included issues were done and closed
