### ISSUE TITLE
Story - Settings menu / Personal - how to change email

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#613]
If a user is willing to change an email

<img width="165" alt="Screenshot at Mar 03 12-02-56" src="https://user-images.githubusercontent.com/107203576/222704296-20408067-fa04-48b4-b6d9-644bb4c51114.png">

Once a user presses 'Contacts' one can see AND not able to EDIT

- Own Email
- Own phone number

Step 1
- Press 'Edit' button 
- Click on one of the inputs 'Email' Or 'Phone' (selected Email - similar for phone)

Step 2
- Entered New email (of it exits then inform and not give permission to change)
- Instead button 'Edit' can 'Save' (click on 'Save')

Step 3
- Continue (it calls new popup with Code)
- Cancel (if click cancel it remains the old email - display screen with email & phone)

<img width="896" alt="Screenshot at Mar 03 12-00-42" src="https://user-images.githubusercontent.com/107203576/222704106-6fdc3b87-cb85-4d89-b079-8cfb697c7723.png">

Step 4
- Enter code
- Confirm (it changes the email for a new one)
- Discard (it remains old email, and cancel email changing process)

<img width="166" alt="Screenshot at Mar 03 12-14-01" src="https://user-images.githubusercontent.com/107203576/222706412-26a6d7d0-cb69-4992-9609-d3b8aeeb0897.png">

**Comment by desperado1802** [comment]
Closing with proof:
https://github.com/ever-co/ever-teams/assets/124465103/9cbd6c5e-451e-4f29-8dc8-97560d24b87b
