### ISSUE TITLE
Feature: integrate command bar

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#619]
See:
* https://github.com/timc1/kbar
* https://github.com/pacocoursey/cmdk
* https://github.com/harshhhdev/kmenu

Basically, it's similar to https://www.commandbar.com, but open-source.
TODO: we need more research, could be more available packages! See https://github.com/topics/command-palette

**Comment by badalkhatri0924** [comment]
@evereq shadcn is also using cmdk, so we will use same.
https://ui.shadcn.com/docs/components/command

**Comment by evereq** [comment]
We already have it @Anishali2 , icon in the header of app :) You click it and it shows a popup with kb shortcuts to run fast actions etc.

![image](https://github.com/ever-co/ever-teams/assets/118497/f8b9bfff-65a2-4e32-b331-31b5fa95b5ff)
