### ISSUE TITLE
Accept Invite inApp

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#643]
If the user is invited to join another team should see Popup

<img width="167" alt="Screenshot at Mar 10 17-46-47" src="https://user-images.githubusercontent.com/107203576/224374082-fb2b2114-84df-4431-9819-cf557e8de47f.png">

**Comment by desperado1802** [comment]
Proof that it's already implemented:
https://github.com/ever-co/ever-teams/assets/124465103/4d196b00-a953-4201-8e23-cb9c7dc3458b
