### ISSUE TITLE
Fixes 5 | Team, Task, Settings pages

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#734]
- [x] In Settings - there is NOT 'back' arrow and The dashboard in the page path does not work (the user should be able to go back)
- [x] Team page - we don't have the ‘Status’ dropdown on the user car under the title we need to add it ONLY for the Team page (on the User Task page should be without Status for each Task card)
- [x] User Task page / Tabs Worked & Assigned - buttons 'Start' should be in 3rd column with Time (not where the progress bar → see Figma design)
- [x] User Task page / Tabs Worked & Assigned & Unassigned - make wider Estimate & Time columns
- [x] User Task page / Tabs Worked & Assigned & Unassigned - if the user refreshes the page it should remember Tab was selected the last time (now it always refers to Worked)
- [x] ~~Team Settings - when a user creates a custom Status, Priority, Size should select a custom icon if not selected in the purpose~~
- [x] Team page - Labels are displayed on user cards, if user reload whole page (but need to be checked code one more time, there is some delay or something wrong)
- [x] If Time tracking is disabled for a user - should not see 'own Task card' on Team page and 'own Task page'
- [x] the Size of Status, Labels, Priorities are still bigger than task titles etc [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/780)
- [x] When the manager deletes only team -> should see the main page without team + button 'Create team' 
- [x] When the manager deletes team and press 'log out' should see the main landing page (Now nothing)
- [x] When the manager deletes own account -> should see the main landing page (Now nothing)
- [x] When the manager tries to 'Remove account' from all teams (within one tenant/workspace) -> should be able to remove from all teams where the user is not a manager [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/805)
- [x] When a user has a few invites to join teams and clicks on ‘Reject’ on one of them, it should close only exactly that notification user ‘Rejected’ (Now it closes all notifications)
- [x] Team page / User card - Progress Bar does not display progress
- [x] User Task page / Task card - Progress Bar does not display progress [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/808)
- [x] Team page / User card - the manager should be able to estimate own and other’s tasks on the user card by clicking the ‘icon’ edit (it used to work)
- [x] Team page / User card / ( … ) Edit Task - user should be able to see the cursor at the end of the Title text inside the input AND the whole title should be selected (it used to work)
- [x] Settings / Team - when the user creates a new Label - should not see the name of the previously created label and the color should be randomly selected
- [x] User Task page / Tabs Worked, Assigned, Unassigned - there are still tasks in the wrong tabs.
          Worked / Now - should display the active user's task
          Worked - should contain only tasks user worked on (even 1-sec worked, even no longer assigned)
          Assigned - should display all tasks user Assigned at the moment (worked, not worked)
          Unassigned - should display all tasks user is not assigned at the moment
- [x] Team page - users don't see each other's 'Total time worked today', 'Worked on Task' on cards [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/798)
- [x] Team page - When the user logged in and had active task from the previous session task - should be able to start tracking time instantly (now the system asks to select the task in order to start tracking time) Solution: The system should make Active the last task user worked [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/798)
- [x] Team page / Main input - if user does not have selected task - user can't select Status, Priority, Size, Label
- [x] Personal Settings - when user is not a part of any team AND 'Delete' own account, should be redirected to the main Landing page 
- [x] Settings / Team - Public Team should be selected by default
- [x] Settings / Team - Public Team does not display Status, Priority, Size, Label - if user select specific (displays only default empty)
- [x] Settings / Personal - change email to another -> should send Code on new email (now does not send)
- [x] Status - we should set default status for each tasks 'First' -> 'Open'(in our case)
- [x] Status - when user select task with any status and start tracking the time (with automation) the status should be 'In progress' without automation - a status is set by the assignee
- [x] Team page - if user closes a task, it should disappear from 'user card' AND from 'the main input' (closed task should be in closed Tab) Should look like her has no task until pick one up [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/784)
- [x] Team page / Main input - if user start typing something unique (create new task) in 3-5 sec the system erases it that is not good. Typed text should be kept until user press enter to confirm task creation OR erase if select any other task or do another action
- [x] Team page / ( ... ) - Remove member - user should be removed from the list of team members (now active user becomes as invited and then manages should remove again)
- [x] Team Avatar - it is updated every 3-5 sec - it looks terrible. We should fix it
- [x] ~~Invite - when User A is part of Team A and User A sees invite from Team B inside the app, should be able to 'accept' and join (see that team in the list of User's A teams) (NOW User A does not see) [SAME TENANT WORKING]~~
- [x] Status on Avatar (green/ orange / red) - team members of newly joined users should see his/her status even they are not selected any task (green with dot OR red)
- [x] Progress Bar - if two or more members work on the same task, they should see the same progress bar, estimate. On live mode progress bar should move 2/3 etc times faster in dependency of how many members are currently tracking the time for the task
- [x] Progress Bar - on User Task page - no progress o task cards (should be displayed the latest progress)[(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/808)
- [x] Public page / Progress Bar - should be updated synchronously as for LIVE view [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/798)- 
- [x] Public page - user's avatar status should be updated right after it is changed
- [x] Public page - task Status, Size, Priority, Label - not always display all of them - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/794)
- [x] Team page - column 'Worked on Task' should be updated in LIVE mode [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/798)
- [x] Settings - change own email to another does not send CODE #587 
- [x] Public page - if user presses 'Requested join' (but has an account) should select Tab 'Already Member' and with own email join and see the normal page as if the user Login from the main landing page (now the user can see Public page only)
- [x] Team page - on cards Titles - remove title 'Status' and Keep only 'Name' title and rest titles that we had
- [x] Team page / Invitation List : User should automatically see if he/she gets any new Invitation (Now user has to refresh it)
- [x] When an employee user Delete Account it gives a forbidden error
- [x] Team Avatar - still works not good
- [x] Team page / Unassign task from yourself - the main input should become empty (now it still shows the assigned task data)
- [x] Team page / Estimation input bug - since the system updates the page every 5 sec if a user enters estimate values and does not have time to save it - the browser update page and all data is lost, and input becomes empty.
- [x] User Task page / Filter - in order to collapse Filter if there are no selected items user should be able to click out of the Filter card
- [x] User Task page - The Column with status has different sizes for each status [Image](https://files.slack.com/files-pri/T0BBDDG2G-F052P2Y6T0T/screenshot_at_apr_11_15-12-34.png)
- [x] App Crashing when the user is not part of any Team
- [x] SUPER_ADMIN User is not able to create a Team  [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/793)
- [x] ~~Time Status API gives 403 error for SUPER_ADMIN~~
- [x] Task timer should be run Team wise
- [x] Multiple Tabs open - If in one tab timer started then it should sync automatically in another tab (Now if we refresh tab then only it sync) [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/808)
- [x] Custom-created Labels can be seen by other teammates without reload the page
- [x] Team page - if a user (manager) disabled Time tracking, User task card should NOT be displayed on Team page [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/814)
- [x] Public page does not display a team - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/844)
- [x] Input of Task Status, Size, Priority and Label automatically removed every 5 seconds [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/817)
- [x] Assigned Manager can NOT 'Remove' Admin (Team Owner) Manager
- [x] Team page / Unassign task from yourself - the main input should become empty (now the unassigned task appears on the user card again - but not assigned until the user starts tracking time)
- [x] 'Start/Stop' button works not well. Sometimes when the user wants to stop the button it is not clickable and vice versa. As the additional button does not change status of the button to Stop or Play [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/824)
- [x] Team page - Label keeps disappearing on changing Status/Size/Priority [(PR)](https://github.com/ever-co/ever-gauzy-teams/issues)
- [x] Team page - Wrong Task Estimation is showing for current active task - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/828)
- [x] Team Settings - If user edit Team name and haven't saved yet it keeps changing to original one after every 5 seconds refresh - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/830)
- [x] Detect Timezone not working in Firefox
- [x] USER TASK PAGE - since the system updates the page every 5 sec if a user enters estimate values and does not have time to save it - the browser update page and all data is lost, and input becomes empty [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/837)
- [x] TEAM PAGE - since the system updates the page every 5 sec if a user type values in main input and does not have time to save it - the browser update page and all data is lost [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/837)
- [x] USER TASK PAGE - Same estimation are considered In all the Task cards - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/835)

- [x] - for invite card and invited user card let's use the format 0h:0m (not  00h: 00m) - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/840)
- [x] - Invitation,  if user  A is online can see the invite inside the app,  when user A invited first time to Team 1 it  works, if the user A was removed form  the team, second time does not see an invite from the same team [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/841)
- [x] - team settings / got an issue when I clicked 'Create new Label' (the system was thinking) then I clicked on 'Create new ..' for size, and priority and got an error. Seems like an issue with API statuses, priorities, sizes, labels creation
- [x] - User Task page / Worked - in the 'Now' section should be displayed only the task the user worked last time TODAY, all previous tasks the user worked on should be in that period it was. - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/846)
- [x] - User Task page-/ TimeTracker should work the same as on Team page (counting time speed) - NOW it works differently.
- [x] - Team page - Estimation input which is under the main input, there's still an issue with entering the estimate while the Time Tracker is on - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/837)
- [x] - User Task page  / Worked - somehow user A just  created task X (nobody  assigned  except user A) can see that task in User Task page / Worked of other teammates (even all tasks user A worked) - [(PR)](https://github.com/ever-co/ever-gauzy-teams/pull/854)
- [x] - The invite user feature does not work for  the users who were removed  from the team (the second time the users can’t be invited -  that is NOT good)
- [x] - Naming (Teams, Members) - only Letters possible in icon or avatar
- [x] - Manager deletes own team (gives an error) - there was one more team member, when the user refreshes the page it displays user account without team

**Comment by badalkhatri0924** [comment]
@KostyaEver 

Can you check `Settings / Personal - change email to another -> should send Code on new email (now does not send)` again? I am getting emails (Checked in stage and production both). It is fixed when we did migrations for an email template. If it is working for you now then we can close this.

**Comment by badalkhatri0924** [comment]
@KostyaEver @evereq 

`When the manager deletes only team -> should see the main page without team + button 'Create team'`

Should we redirect to the main page?

Currently, when we Manager Dispose the only team we are opening Popup as shown below.
And if the manager closes the popup in the Team setting we are already showing Create new Team button.

I think it is not necessary here to redirect to main page as Team setting and Main page UI is almost same for Create new Team button.


<img width="1440" alt="image" src="https://user-images.githubusercontent.com/81486442/229979376-9c99bb85-d6d4-4aa8-a534-f76148371ea1.png">

**Comment by badalkhatri0924** [comment]
@evereq @KostyaEver 
`Settings / Team - Public Team should be selected by default`

In my opinion, the team should be Private by default (The current implementation is the same), Not all the users/managers will want the team to be public by default.

Let me know your thoughts on this why we need to make default Public.

**Comment by KostyaEver** [comment]
> @KostyaEver @evereq
> 
> `When the manager deletes only team -> should see the main page without team + button 'Create team'`
> 
> Should we redirect to the main page?
> 
> Currently, when we Manager Dispose the only team we are opening Popup as shown below. And if the manager closes the popup in the Team setting we are already showing Create new Team button.
> 
> I think it is not necessary here to redirect to main page as Team setting and Main page UI is almost same for Create new Team button.
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/81486442/229979376-9c99bb85-d6d4-4aa8-a534-f76148371ea1.png">
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/81486442/229979621-04aceae5-b1e6-4a4f-8039-1d25abb0a440.png">

@badalkhatri0924 
My bad, so here everything is ok, just the problem that when the user delete team and logout it does not redirect to the main landing page (Login / Create team)

**Comment by badalkhatri0924** [comment]
> > @KostyaEver @evereq
> > `When the manager deletes only team -> should see the main page without team + button 'Create team'`
> > Should we redirect to the main page?
> > Currently, when we Manager Dispose the only team we are opening Popup as shown below. And if the manager closes the popup in the Team setting we are already showing Create new Team button.
> > I think it is not necessary here to redirect to main page as Team setting and Main page UI is almost same for Create new Team button.
> > <img alt="image" width="1440" src="https://user-images.githubusercontent.com/81486442/229979376-9c99bb85-d6d4-4aa8-a534-f76148371ea1.png">
> > <img alt="image" width="1440" src="https://user-images.githubusercontent.com/81486442/229979621-04aceae5-b1e6-4a4f-8039-1d25abb0a440.png">
> 
> @badalkhatri0924 My bad, so here everything is ok, just the problem that when the user delete team and logout it does not redirect to the main landing page (Login / Create team)

I've fixed this today @KostyaEver.

**Comment by paradoxe35** [comment]
>  Team Settings - when a user creates a custom Status, Priority, Size should select a custom icon if not selected in the purpose

@badalkhatri0924 
we need a API to upload a custom task status icon

**Comment by badalkhatri0924** [comment]
> > Team Settings - when a user creates a custom Status, Priority, Size should select a custom icon if not selected in the purpose
> 
> @badalkhatri0924 we need an API to upload a custom task status icon

@paradoxe35 @KostyaEver I think custom icon upload we aren't doing in v1.
@KostyaEver As I remember we decided that we might be using some libraries to show available icons.

**Comment by KostyaEver** [comment]
> > > Team Settings - when a user creates a custom Status, Priority, Size should select a custom icon if not selected in the purpose
> > 
> > 
> > @badalkhatri0924 we need an API to upload a custom task status icon
> 
> @paradoxe35 @KostyaEver I think custom icon upload we aren't doing in v1. @KostyaEver As I remember we decided that we might be using some libraries to show available icons.

Thoughts about 'Custom icon'
Here I meant that it is any icon within the available list of icons and color (random selection). So once the user creates new Status or Priority or Size - the system should select any of the available icons and colors (for sure user can select any).
Example: the user is about to create new Size and call it 'Dog' so the system should select any icon.

Yes @badalkhatri0924 is right we are going to use an existing library (seems like we already use it)

@paradoxe35 @badalkhatri0924 

Please, correct me @evereq if I am wrong

**Comment by badalkhatri0924** [comment]
> > > > Team Settings - when a user creates a custom Status, Priority, Size should select a custom icon if not selected in the purpose
> > > 
> > > 
> > > @badalkhatri0924 we need an API to upload a custom task status icon
> > 
> > 
> > @paradoxe35 @KostyaEver I think custom icon upload we aren't doing in v1. @KostyaEver As I remember we decided that we might be using some libraries to show available icons.
> 
> Thoughts about 'Custom icon' Here I meant that it is any icon within the available list of icons and color (random selection). So once the user creates new Status or Priority or Size - the system should select any of the available icons and colors (for sure user can select any). Example: the user is about to create new Size and call it 'Dog' so the system should select any icon.
> 
> Yes @badalkhatri0924 is right we are going to use an existing library (seems like we already use it)
> 
> @paradoxe35 @badalkhatri0924
> 
> Please, correct me @evereq if I am wrong

@KostyaEver We are not using any library as of now. We are showing static list which is already uploaded to backend.

May be for this We can select 1st icon by default while creating new status/label etc...

**Comment by KostyaEver** [comment]
> > > > > Team Settings - when a user creates a custom Status, Priority, Size should select a custom icon if not selected in the purpose
> > > > 
> > > > 
> > > > @badalkhatri0924 we need an API to upload a custom task status icon
> > > 
> > > 
> > > @paradoxe35 @KostyaEver I think custom icon upload we aren't doing in v1. @KostyaEver As I remember we decided that we might be using some libraries to show available icons.
> > 
> > 
> > Thoughts about 'Custom icon' Here I meant that it is any icon within the available list of icons and color (random selection). So once the user creates new Status or Priority or Size - the system should select any of the available icons and colors (for sure user can select any). Example: the user is about to create new Size and call it 'Dog' so the system should select any icon.
> > Yes @badalkhatri0924 is right we are going to use an existing library (seems like we already use it)
> > @paradoxe35 @badalkhatri0924
> > Please, correct me @evereq if I am wrong
> 
> @KostyaEver We are not using any library as of now. We are showing static list which is already uploaded to backend.
> 
> May be for this We can select 1st icon by default while creating new status/label etc...

ok, I see.
we can use 1st as you said OR is it difficult to add a method where the system randomly selects any available icon and color?

**Comment by badalkhatri0924** [comment]
> > > > > > Team Settings - when a user creates a custom Status, Priority, Size should select a custom icon if not selected in the purpose
> > > > > 
> > > > > 
> > > > > @badalkhatri0924 we need an API to upload a custom task status icon
> > > > 
> > > > 
> > > > @paradoxe35 @KostyaEver I think custom icon upload we aren't doing in v1. @KostyaEver As I remember we decided that we might be using some libraries to show available icons.
> > > 
> > > 
> > > Thoughts about 'Custom icon' Here I meant that it is any icon within the available list of icons and color (random selection). So once the user creates new Status or Priority or Size - the system should select any of the available icons and colors (for sure user can select any). Example: the user is about to create new Size and call it 'Dog' so the system should select any icon.
> > > Yes @badalkhatri0924 is right we are going to use an existing library (seems like we already use it)
> > > @paradoxe35 @badalkhatri0924
> > > Please, correct me @evereq if I am wrong
> > 
> > 
> > @KostyaEver We are not using any library as of now. We are showing static list which is already uploaded to backend.
> > May be for this We can select 1st icon by default while creating new status/label etc...
> 
> ok, I see. we can use 1st as you said OR is it difficult to add a method where the system randomly selects any available icon and color?

@KostyaEver we can do random too. will take almost same time.

**Comment by paradoxe35** [comment]
The random features has been implemented already @KostyaEver

**Comment by badalkhatri0924** [comment]
> The random color features has been implemented already @KostyaEver

Yup, random color is done but icon is pending.

@paradoxe35 @KostyaEver I'll do it.

**Comment by evereq** [comment]
> > > > > > Team Settings - when a user creates a custom Status, Priority, Size should select a custom icon if not selected in the purpose
> > > > > 
> > > > > 
> > > > > @badalkhatri0924 we need an API to upload a custom task status icon
> > > > 
> > > > 
> > > > @paradoxe35 @KostyaEver I think custom icon upload we aren't doing in v1. @KostyaEver As I remember we decided that we might be using some libraries to show available icons.
> > > 
> > > 
> > > Thoughts about 'Custom icon' Here I meant that it is any icon within the available list of icons and color (random selection). So once the user creates new Status or Priority or Size - the system should select any of the available icons and colors (for sure user can select any). Example: the user is about to create new Size and call it 'Dog' so the system should select any icon.
> > > Yes @badalkhatri0924 is right we are going to use an existing library (seems like we already use it)
> > > @paradoxe35 @badalkhatri0924
> > > Please, correct me @evereq if I am wrong
> > 
> > 
> > @KostyaEver We are not using any library as of now. We are showing static list which is already uploaded to backend.
> > May be for this We can select 1st icon by default while creating new status/label etc...
> 
> ok, I see. we can use 1st as you said OR is it difficult to add a method where the system randomly selects any available icon and color?

Just select one icon, not random please. Make sure that icon mean something more or less universal

**Comment by evereq** [comment]
Please do not select random icon, it's for sure bad idea. Select one icon by default that looks generic, e.g. some empty circle or dot etc. Color random is good, but icon is bad

**Comment by badalkhatri0924** [comment]
@KostyaEver @evereq May be by default we can select 1st one?

<img width="424" alt="image" src="https://user-images.githubusercontent.com/81486442/230854692-e26c2633-1b9d-4188-a52b-24150b7c37b1.png">
