### ISSUE TITLE
Login Update

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#740]
If the user logs in to the system

Update the Login screens to the next

1. Main screen (selects 'Login')
<img width="164" alt="Screenshot at Mar 31 12-25-22" src="https://user-images.githubusercontent.com/107203576/229095506-7dda454b-f687-4b45-b78d-81e01ffb7a96.png">

2. User should enter only Email and press 'Continue' OR 'Back'
<img width="168" alt="Screenshot at Mar 31 12-22-48" src="https://user-images.githubusercontent.com/107203576/229095213-1002030d-8698-46ec-b071-91f295a284a9.png">

3. User should enter 'Code' and press 'Join' OR 'Back'
<img width="166" alt="Screenshot at Mar 31 12-23-11" src="https://user-images.githubusercontent.com/107203576/229095271-bbe2b165-21e8-4f8d-afba-fbe930273ba8.png">

**Comment by desperado1802** [comment]
The login flow is no longer exactly same as described in the issue. One more step is added. Closing with proof:
https://github.com/ever-co/ever-teams/assets/124465103/80733fac-61bf-4c38-942e-bd364613e005
