### ISSUE TITLE
Bugs | Login / Create Team screens

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#819]
- [x] - The login screen is not updated (Email and Code should be different screens) #740 
- [x] - Screen 'Create Team' User should not be able to press 'continue' without entering Code
- [x] - Screen 'Create Team' main - Instead of 'Login' is still 'Join existing team' (Android)
- [x] - Screen 'Create Team' main - user should not be able to press 'Create team' with empty 'Team name' input
- [x] - Screen 'Create Team' - once the user entered Name & Email and pressed 'Create team', the team was NOT created (Android)
- [x] - Screen 'Email and Code' - when the user presses 'Resend code' - the code is not sent. Fix a Code Dispatching

- [x] - General - Each task should have the status 'Open' by default (in settings we will define any name later)
- [x] - General - let's add automation if a user starts tracking time on any task it should have the status 'In progress'
- [x] - General - 'Create Team' - inApp - input to enter a  name should NOT be hidden by  keyboard, add above the keyboard
- [x] - General - Check All inputs ^ like create a team -in order to  prevent hidden input by keyboard
- [x] - General - Make sure that all Dropdown menus (like Teams selection) can be collapsed by clicking out of the dropdown menu AND ( ... ) menu
- [x] - General -  'Round Estimate' does not  display Green progress if task has estimate

- [x] - User tasks screen  - task 'Status' is displayed as an 'arrow' only, should be an icon as on Figma
- [x] - User tasks screen  - task cards have no 'Type', should be an icon as on Figma
- [x] - User tasks screen  - 'Priority' and 'Size', should be next to task title as small icons on Figma
- [x] - User tasks screen  - 'Filter' does not  work
- [x] - User tasks screen  - 'Filter' user first should see 'Reset' & 'Apply' buttons and 'Status', 'Priorities', 'Labels', 'Sizes' Popup, Sub-popup  should only be opened when click on one of the options
- [x] - User tasks screen - ( ... ) Edit and Estimate options do NOT work
- [x] -  User tasks screen  - 'Total time' rename  to 'Total work' (in Figma mistake)
- [x] - User tasks screen  - 'Total work' does not display the total time the user worked on this task for days/weeks/month

- [x] - Team screen - user card - two times display 'Size', should be 'Status' first under a task title and then 'Labels'
- [x] - Team screen  - 'Priority' and 'Size', should be ext to task title as small icons on Figma
- [x] - Task type (Epic, Task, Story, Bug) - should be able to change (only exception if the user created Epic, it can not be changed - only close or delete)
- [x] - Team screen - ( ... ) menu 'Edit' and 'Estimate' options do NOT work
- [x] - Team screen - uncollapsed team list- can be collapsed by clicking 'arrow' up and clicking out of 'uncollapsed team's list'.  Note: 'Team's list' should be modal - other widgets can't be clickable.
- [x] - Team screen - 'Total time' does not display time user worked (Total time user worked today)
- [x] - Team screen - 'Total work' does not display time user worked (Total work user worked on that task not only today)

- [x] - MyWork screen - uncollapsed team list- can be collapsed by clicking 'arrow' up and clicking out of 'uncollapsed team's list'.  Note: 'Team's list' should be modal - other widgets can't be clickable.
- [x] - MyWork screen - Modal 'Create new Team' should be able to see when the user is typing (on the phone keyboard) a team name.
- [x] - MyWork screen - Modal 'Create new Team', button 'Send' rename to 'Create'
- [x] - MyWork screen - clicking on the task 'type icon' should be able  to see Modal with types OR not see if the task has Epic type
- [x] - MyWork screen - 'Status' on a list of  tasks look like only 'Arrow'
- [x] - MyWork screen - 'Status' on a list of  tasks should look like small icon + arrow, please see Figma
- [x] - MyWork screen - user can't create Empty task
- [x] - MyWork screen - Estimate - NO way to save it. Should be saved either click out of the input OR modal popup with Cancel or Confirm

- [x] - Personal Setting screen - Avatar is not saved
- [x] - Personal Setting screen - Full Name is not saved

- [x] - Avatars should not blim (due to auto-update) and should  stay as normal
- [x] - MyWork screen / main input - should be able to select type of issue (Epic/ Task / Story / Bug / Custom) - now only bug I can see
- [x] - MyWork screen / combo box - I can't scroll all tasks - not scroll
- [x] - MyWork screen / combobox - Statuses should be displayed only small icons (see Figma) now it displays with some  text
- [x] - MyWork screen / main input -  here is no way to highlight  all text of a task title in  order to delete or edit etc
- [x] - MyWork screen - button 'Start' not centered well

**Comment by desperado1802** [comment]
Removed: - [ ] - General - let's add automation if a user starts tracking time on another task it should set the status 'Open' if the previous task if the user has NOT finished that previous task. As there is issue already, it will be for v2

**Comment by desperado1802** [comment]
All checks are checked
