### ISSUE TITLE
Story | Active task Logic

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#834]
**Active task - is a task that is selected by User**

1. When a task selecting in UI for a given employee, you send a request to the server to assign the task to an employee (single request)

2. When the app loads / data reloads (refresh happens), you get a task from a server on which the employee right now tracking time (if any such task exists!). Such tasks that employee tracking time must be automatically selected in UI, and timer control should show tracking time

3. You can also store in the localStorage (cookie, but really better local storage) last selected task and display it on page refresh / reload unless some task time tracking is on (see above)

---
### Status
- [x] Web
- [x] Mobile

**Comment by desperado1802** [comment]
Closing as it's implemented to both Mobile and Web. Merged PR's are the proof
