### ISSUE TITLE
Settings | Team - Color

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#881]
The user should be able to select/change the Team color

Here should be used library for colors (it might be similar to that is used for Status, Labels etc)

Note: The system randomly selects any color if the user did not select

<img width="769" alt="Screenshot at May 19 12-06-41" src="https://github.com/ever-co/ever-gauzy-teams/assets/107203576/51fe2e30-f328-4866-99c6-179fe6349527">

**Comment by evereq** [comment]
No, we don't need to show such popup, the selector that allow to select any color is better option :)

![image](https://github.com/ever-co/ever-teams/assets/118497/37240809-8bee-4f64-83c6-749cd2993425)

Closing this issue as completed.
