### ISSUE TITLE
[Feature] Epics and Task with sub-tasks

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#937]
Epic page is almost similar to the Task page  with a slight difference

- Title does not contain issues with hierarchy (only number + type 'Epic')
- Can be a full list of Assignees (who work on any single task of the Epict is seen in assignees)
- Estimate (displays a summary of all task estimates AND how many task estimated and NO)
- Time block (displays tracked time  on summary of Epic tasks)

Notes:
1. some of the above requirements also should be true when we look into Tasks with sub-tasks, e.g. it should show a full list of assignees to all sub-tasks, it should show "estimate" as a sum of all sub-tasks), time block - same should be summary, etc. 
2. we need somehow show separate values for Epic estimate and estimates from tasks inside Epic and same with Time Tracking in case if time was tracked for Epic itself or for stories/tasks inside it and so on. I.e. looking into issue (Epic / Task) with some 'sub-tasks' inside of it, we should be able to distinguish when some metric is about parent itself or about all children (another example - assigned people, we should be able to see who assigned to Epic itself and who assigned to sub-tasks inside of it). 

Page

<img width="833" alt="Screenshot at May 30 12-54-34" src="https://github.com/ever-co/ever-gauzy-teams/assets/107203576/6f0124ff-f378-4ac6-b90d-0c341369509e">

**Comment by GloireMutaliko21** [comment]
Sir @evereq / @KostyaEver it seems that the current task page already differentiates the display according to whether a task is "Epic" or not.
Are there any more details or precisions yet to be implemented in relation to what we currently have concerning this ticket ?
