### ISSUE TITLE
BUG | When create new team by default it is showing static time

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#961]
![gt-default-time](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/a7c15e03-9066-4685-ab37-baeab0946c5b)

https://github.com/ever-co/ever-gauzy-teams/assets/81486442/ebade287-732e-4998-bb72-e72584d638d9

**Comment by desperado1802** [comment]
Proof that the issue is not present anymore: 

https://github.com/ever-co/ever-teams/assets/124465103/db98b788-d131-4f2f-8ec4-5ed4a914e3b6
