### ISSUE TITLE
BUG | Unnecessary API calling 

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#965]
POST /api/timesheet/time-slot is being called when the timer is not running, ideally, it should be called when the timer is running

Other APIs are also being called Unnecessarily

https://github.com/ever-co/ever-gauzy-teams/assets/81486442/660ca996-6441-4b83-a88a-501236b1feec

https://github.com/ever-co/ever-teams/assets/81486442/9ae72713-e490-4d2f-9e5f-41278754a168

**Comment by desperado1802** [comment]
Calling unnecessary api/organization-team-employee/${id} is fixed in PR [#1333](https://github.com/ever-co/ever-teams/pull/1333)
