### ISSUE TITLE
[BUG] Change Timer running Icon at all places

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#985]
Not running Mobile:
![simulator_screenshot_C060B540-AAB1-4033-9F97-3BB042232415](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/a7aa1b37-37b8-4f91-a097-6e5e5430baf7)

Running Mobile:
![simulator_screenshot_4FFEB65A-C54B-46E1-B9B3-D4BC00766B5D](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/7fff7c75-b71e-4754-a704-492a27d41b5e)

Not running Web:
<img width="1438" alt="image" src="https://github.com/ever-co/ever-gauzy-teams/assets/81486442/8799497f-9ecb-4ab0-b8d5-6b43a737a14a">

Running Web:
<img width="1439" alt="image" src="https://github.com/ever-co/ever-gauzy-teams/assets/81486442/1f9feb1f-6f11-48e4-a491-9092904ad6fc">

**Comment by desperado1802** [comment]
Timer running icon is updated at all places, it's same as WEB:
![File (8)](https://github.com/ever-co/ever-teams/assets/124465103/0a03f2e2-127b-4e0e-8d35-f3bf4869310f)
![File (7)](https://github.com/ever-co/ever-teams/assets/124465103/9df6cb60-46b6-4731-bc65-75816da8e2e7)
